// catalog-vision-api mixin — public API endpoints for UIL/CTE catalog,
// competition templates, vision document v2, funding tracker, and impact.
// LEX_SOVEREIGNUS: All data is deterministic and sovereign.

import CatalogVisionLib "../lib/catalog-vision";
import Types "../types/catalog-vision";
import RcgnLib "../lib/rcgn";
import NomsLib "../lib/noms";
import AchvLib "../lib/achv";
import Time "mo:core/Time";

mixin (
  fundingStore : CatalogVisionLib.FundingStore,
  rcgnStore    : RcgnLib.RcgnStore,
  nomStore     : NomsLib.NomStore,
  achvStore    : AchvLib.AchvStore,
) {

  // ── Course Catalog ────────────────────────────────────────────────────────

  /// Return all catalog courses across all 18 UIL/CTE categories.
  public query func getCatalog() : async [Types.CatalogCourse] {
    CatalogVisionLib.getCatalog();
  };

  /// Return course detail with Fibonacci-spaced modules for a given courseId.
  public query func getCourseDetail(courseId : Text) : async ?Types.CatalogCourseDetail {
    CatalogVisionLib.getCourseDetail(courseId);
  };

  // ── Competition Templates ─────────────────────────────────────────────────

  /// Return all competition prep templates for the Self-Study Creator.
  public query func getCompetitionTemplates() : async [Types.CompetitionTemplate] {
    CatalogVisionLib.getCompetitionTemplates();
  };

  // ── Vision Document v2 ────────────────────────────────────────────────────

  /// Return the full Sovereign Vision Document v2, generated by the Architecture Council.
  /// Includes founder story, Diego Protocol, impact case, market gap, and live stats.
  public query func getVisionDocumentV2() : async Types.VisionDocumentV2 {
    CatalogVisionLib.getVisionDocumentV2(rcgnStore, nomStore, achvStore);
  };

  // ── Funding Tracker ───────────────────────────────────────────────────────

  /// Record a new funding program entry.
  /// stage: "IDENTIFIED" | "APPLIED" | "PENDING" | "AWARDED" | "DECLINED"
  public shared func recordFundingEntry(
    entry : Types.FundingEntryInput,
  ) : async Types.FundingEntryResult {
    CatalogVisionLib.recordFundingEntry(fundingStore, entry, Time.now());
  };

  /// Return all funding tracker entries.
  public query func getFundingTracker() : async [Types.FundingEntry] {
    CatalogVisionLib.getFundingTracker(fundingStore);
  };

  // ── Impact Calculator ─────────────────────────────────────────────────────

  /// Compute platform impact for a given school count and average school size.
  public query func computeImpact(
    schoolCount       : Nat,
    studentsPerSchool : Nat,
  ) : async Types.ImpactResult {
    CatalogVisionLib.computeImpact(schoolCount, studentsPerSchool);
  };
};
