import { createActor } from "@/backend";
import type { FundingTarget, VisionDocument, VisionStats } from "@/backend";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useVisionWithFunding } from "@/hooks/use-principal-intelligence";
import { useActor, useInternetIdentity } from "@caffeineai/core-infrastructure";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import {
  Award,
  BookOpen,
  BrainCircuit,
  ChevronLeft,
  GraduationCap,
  Heart,
  Layers,
  RefreshCw,
  Shield,
  Sparkles,
  Star,
  TrendingUp,
  Wallet,
} from "lucide-react";
import { motion } from "motion/react";
import { useState } from "react";

// ─── Existing hooks ─────────────────────────────────────────────────────────────────
function useVisionDocument() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<VisionDocument>({
    queryKey: ["vision-document"],
    queryFn: async () => {
      if (!actor)
        return {
          foundingStory: "",
          platformVision: "",
          technicalSovereignty: "",
          impactCase: "",
          fundingStrategy: "",
          liveStats: {
            totalStudentsFlagged: 0n,
            achievementsSealed: 0n,
            nominationsSent: 0n,
          },
        };
      return actor.generateVisionDocument();
    },
    enabled: !!actor && !isFetching,
    staleTime: 21_000,
  });
}

function useVisionStats() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<VisionStats>({
    queryKey: ["vision-stats"],
    queryFn: async () => {
      if (!actor)
        return {
          totalStudentsFlagged: 0n,
          achievementsSealed: 0n,
          nominationsSent: 0n,
        };
      return actor.getVisionStats();
    },
    enabled: !!actor && !isFetching,
    refetchInterval: 21_000,
  });
}

// ─── Status badge for funding targets ────────────────────────────────────────────────────
function FundingStatusBadge({ status }: { status: string }) {
  const map: Record<string, { bg: string; color: string; text: string }> = {
    Identifying: {
      bg: "rgba(100,100,255,0.12)",
      color: "oklch(0.72 0.17 270)",
      text: "IDENTIFYING",
    },
    "In Progress": {
      bg: "rgba(255,185,0,0.12)",
      color: "oklch(0.75 0.16 70)",
      text: "IN PROGRESS",
    },
    Submitted: {
      bg: "rgba(0,210,255,0.12)",
      color: "oklch(0.78 0.22 200)",
      text: "SUBMITTED",
    },
    Funded: {
      bg: "rgba(0,220,130,0.15)",
      color: "oklch(0.72 0.17 155)",
      text: "FUNDED ✓",
    },
  };
  const style = map[status] ?? map.Identifying;
  return (
    <span
      className="inline-flex items-center rounded-lg px-2 py-0.5 font-mono text-[9px] font-bold"
      style={{
        background: style.bg,
        color: style.color,
        border: `1px solid ${style.color}40`,
      }}
    >
      {style.text}
    </span>
  );
}

// ─── Funding Tracker Section ────────────────────────────────────────────────────────
function FundingTracker({
  targets,
  isLoading,
}: {
  targets: FundingTarget[];
  isLoading: boolean;
}) {
  const AMBER = "oklch(0.75 0.16 70)";
  return (
    <motion.section
      id="funding-tracker"
      data-ocid="vision.funding_tracker_section"
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="glass rounded-2xl p-6 md:p-8 scroll-mt-20"
    >
      <div className="flex items-center gap-3 mb-6">
        <div
          className="h-10 w-10 rounded-xl flex items-center justify-center"
          style={{
            background: "rgba(255,185,0,0.12)",
            border: "1px solid rgba(255,185,0,0.30)",
          }}
        >
          <Wallet className="h-5 w-5" style={{ color: AMBER }} />
        </div>
        <div>
          <h2 className="font-display font-black text-xl text-foreground">
            Funding Tracker
          </h2>
          <p className="text-xs text-muted-foreground mt-0.5">
            Live status of funding initiatives — generated by COGT+META+AUTN
          </p>
        </div>
      </div>
      {isLoading ? (
        <div className="space-y-3">
          {[1, 2, 3].map((k) => (
            <Skeleton key={k} className="h-16 rounded-xl" />
          ))}
        </div>
      ) : targets.length === 0 ? (
        <div
          className="text-center py-8 text-sm text-muted-foreground"
          data-ocid="vision.funding_tracker.empty_state"
        >
          No funding targets defined yet.
        </div>
      ) : (
        <div className="space-y-3">
          {targets.map((target, i) => (
            <motion.div
              key={`${target.name}-${i}`}
              data-ocid={`vision.funding_target.${i + 1}`}
              initial={{ opacity: 0, x: -8 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.35, delay: i * 0.07 }}
              className="rounded-xl px-5 py-4 flex items-center justify-between gap-4"
              style={{
                background: "rgba(255,185,0,0.04)",
                border: "1px solid rgba(255,185,0,0.12)",
              }}
            >
              <div className="flex items-center gap-3 min-w-0">
                <div
                  className="h-8 w-8 rounded-lg flex items-center justify-center shrink-0 font-mono font-bold text-xs"
                  style={{
                    background: "rgba(255,185,0,0.10)",
                    border: "1px solid rgba(255,185,0,0.22)",
                    color: AMBER,
                  }}
                >
                  {i + 1}
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-semibold text-foreground truncate">
                    {target.name}
                  </p>
                  <p
                    className="text-[10px] font-mono mt-0.5"
                    style={{ color: "rgba(255,185,0,0.65)" }}
                  >
                    {target.amount}
                  </p>
                </div>
              </div>
              <FundingStatusBadge status={target.status} />
            </motion.div>
          ))}
        </div>
      )}
    </motion.section>
  );
}

// ─── Founder Story Section ───────────────────────────────────────────────────────────
function FounderStorySection({
  founderStory,
  isLoading,
}: {
  founderStory: string;
  isLoading: boolean;
}) {
  const AMBER = "oklch(0.75 0.16 70)";
  // Use live data from backend if available, fallback to canonical story
  const storyText =
    founderStory.trim().length > 10
      ? founderStory
      : "Alfredo Medina Hernandez grew up in the public schools of Ferris, Texas — a small district that, by state metrics, sits in the bottom half for math performance. But inside that school, a geometry teacher noticed something: one student was consistently scoring 100 in geometry.\n\nThat teacher didn't wait for an announcement. They submitted Alfredo's name to a national recognition program. A packet arrived. The trip was fully paid. Alfredo flew to Orlando with thousands of students from across the United States — a professional convention, a yearbook, recognition from a program that saw what the school's own infrastructure had no way to surface automatically.\n\nThe recognition happened. But it happened by accident. One teacher. One act. No system to guarantee it for the next student.\n\nEduAI is built to close that gap. Not by replacing teachers — but by making sure the teacher never has to be the only one watching. The system watches too. RCGN flags excellence. NOMS surfaces nominations. ACHV seals every achievement permanently in the student's passport. The next Alfredo doesn't need to wait for one teacher to happen to notice. The intelligence already knows. The pathway is already open.";

  return (
    <motion.section
      id="founding"
      data-ocid="vision.founding_section"
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="scroll-mt-20"
    >
      <div
        className="rounded-2xl p-6 md:p-8 relative overflow-hidden"
        style={{
          background:
            "linear-gradient(135deg, rgba(255,185,0,0.06) 0%, rgba(255,185,0,0.02) 50%, transparent 100%)",
          border: "1px solid rgba(255,185,0,0.20)",
          boxShadow: "0 0 40px rgba(255,185,0,0.06)",
        }}
      >
        {/* Decorative glow */}
        <div
          className="pointer-events-none absolute -top-12 -right-12 h-40 w-40 rounded-full"
          style={{
            background:
              "radial-gradient(circle, rgba(255,185,0,0.15) 0%, transparent 70%)",
          }}
        />
        <div className="flex items-center gap-3 mb-6">
          <div
            className="h-10 w-10 rounded-xl flex items-center justify-center"
            style={{
              background: "rgba(255,185,0,0.15)",
              border: "1px solid rgba(255,185,0,0.35)",
              boxShadow: "0 0 14px rgba(255,185,0,0.20)",
            }}
          >
            <Heart className="h-5 w-5" style={{ color: AMBER }} />
          </div>
          <div>
            <h2 className="font-display font-black text-xl text-foreground">
              Why This Platform Exists
            </h2>
            <p
              className="text-xs font-mono mt-0.5"
              style={{ color: "rgba(255,185,0,0.65)" }}
            >
              Alfredo Medina Hernandez · Ferris High School, Texas
            </p>
          </div>
        </div>

        {/* NSHSS recognition callout */}
        <div
          className="rounded-xl px-4 py-3 mb-6 flex items-start gap-3"
          style={{
            background: "rgba(255,185,0,0.08)",
            border: "1px solid rgba(255,185,0,0.22)",
          }}
        >
          <Award className="h-4 w-4 mt-0.5 shrink-0" style={{ color: AMBER }} />
          <div className="text-xs leading-relaxed" style={{ color: AMBER }}>
            <span className="font-bold">
              National Society of High School Scholars (NSHSS)
            </span>{" "}
            — Selected twice for national recognition in mathematics and
            science. Fully sponsored trip to Orlando, Florida. Professional
            national yearbook. Students from all 50 states. Nominated by a
            geometry teacher at Ferris High School after a student scored 100 in
            geometry.
          </div>
        </div>

        {isLoading ? (
          <div className="space-y-3">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-5/6" />
            <Skeleton className="h-4 w-4/6" />
          </div>
        ) : (
          <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
            {storyText
              .split("\n")
              .filter((p) => p.trim())
              .map((para, _i) => (
                <p key={para.slice(0, 20)}>{para}</p>
              ))}
          </div>
        )}

        <div
          className="mt-6 pt-4 flex items-center gap-2"
          style={{ borderTop: "1px solid rgba(255,185,0,0.12)" }}
        >
          <BrainCircuit className="h-3.5 w-3.5" style={{ color: AMBER }} />
          <p
            className="text-[10px] font-mono"
            style={{ color: "rgba(255,185,0,0.60)" }}
          >
            Architecture council attribution: COGT + META + AUTN — this story is
            the founding data point for the RCGN recognition pipeline.
          </p>
        </div>
      </div>
    </motion.section>
  );
}

// ─── Section block ──────────────────────────────────────────────────────────────────
function SectionBlock({
  id,
  icon: Icon,
  title,
  content,
  accentColor,
  isLoading,
}: {
  id: string;
  icon: React.ElementType;
  title: string;
  content: string;
  accentColor: string;
  isLoading: boolean;
}) {
  return (
    <motion.section
      id={id}
      data-ocid={`vision.${id}_section`}
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="glass rounded-2xl p-6 md:p-8 scroll-mt-20"
    >
      <div className="flex items-center gap-3 mb-6">
        <div
          className="h-10 w-10 rounded-xl flex items-center justify-center"
          style={{
            background: `color-mix(in oklch, ${accentColor} 12%, transparent)`,
            border: `1px solid color-mix(in oklch, ${accentColor} 30%, transparent)`,
          }}
        >
          <Icon className="h-5 w-5" style={{ color: accentColor }} />
        </div>
        <h2 className="font-display font-black text-xl text-foreground">
          {title}
        </h2>
      </div>
      {isLoading ? (
        <div className="space-y-3">
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-5/6" />
          <Skeleton className="h-4 w-4/6" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-3/4" />
        </div>
      ) : (
        <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
          {content
            .split("\n")
            .filter((p) => p.trim())
            .map((para, _i) => (
              <p key={`${id}-${para.slice(0, 10)}`}>{para}</p>
            ))}
        </div>
      )}
    </motion.section>
  );
}

// ─── Main ───────────────────────────────────────────────────────────────────────────
export default function Vision() {
  const { login, isAuthenticated } = useInternetIdentity();
  const { data: doc, isLoading: docLoading, refetch } = useVisionDocument();
  const { data: stats, isLoading: statsLoading } = useVisionStats();
  const { data: funding, isLoading: fundingLoading } = useVisionWithFunding();
  const { actor } = useActor(createActor);
  const [paperText, setPaperText] = useState("");
  const [paperLoading, setPaperLoading] = useState(false);

  const founderStory = funding?.founderStory ?? doc?.foundingStory ?? "";
  const totalStudents = funding ? Number(funding.totalStudents) : null;
  const totalRecognitions = funding ? Number(funding.totalRecognitions) : null;
  const activePrograms = funding ? Number(funding.activePrograms) : null;
  const fundingTargets: FundingTarget[] = funding?.fundingTargets ?? [];

  const NAV_SECTIONS = [
    {
      id: "founding",
      label: "Why It Exists",
      icon: Heart,
      anchor: "#founding",
    },
    {
      id: "vision",
      label: "Platform Vision",
      icon: Sparkles,
      anchor: "#vision",
    },
    {
      id: "sovereignty",
      label: "Technical Sovereignty",
      icon: Shield,
      anchor: "#sovereignty",
    },
    { id: "impact", label: "Impact Case", icon: TrendingUp, anchor: "#impact" },
    {
      id: "funding-tracker",
      label: "Funding Tracker",
      icon: Wallet,
      anchor: "#funding-tracker",
    },
    {
      id: "funding",
      label: "Funding Strategy",
      icon: BookOpen,
      anchor: "#funding",
    },
  ];

  const contentSections = [
    {
      id: "vision",
      icon: Sparkles,
      title: "Platform Vision",
      content: doc?.platformVision ?? "",
      color: "oklch(0.62 0.2 260)",
    },
    {
      id: "sovereignty",
      icon: Shield,
      title: "Technical Sovereignty",
      content: doc?.technicalSovereignty ?? "",
      color: "oklch(0.72 0.17 155)",
    },
    {
      id: "impact",
      icon: TrendingUp,
      title: "Impact Case",
      content: doc?.impactCase ?? "",
      color: "oklch(0.78 0.22 200)",
    },
    {
      id: "funding",
      icon: BookOpen,
      title: "Funding Strategy",
      content: doc?.fundingStrategy ?? "",
      color: "oklch(0.68 0.18 280)",
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 glass-max border-b border-white/5">
        <div className="max-w-5xl mx-auto px-5 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="sm"
              asChild
              data-ocid="vision.back_button"
            >
              <Link to="/">
                <ChevronLeft className="h-4 w-4 mr-1" />
                Back
              </Link>
            </Button>
            <span className="text-muted-foreground text-sm">/</span>
            <span className="text-sm font-medium">Sovereign Vision</span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => refetch()}
              data-ocid="vision.refresh_button"
              className="gap-1.5 text-xs"
              type="button"
            >
              <RefreshCw className="h-3.5 w-3.5" />
              Regenerate
            </Button>
            {!isAuthenticated && (
              <Button
                size="sm"
                onClick={() => login()}
                data-ocid="vision.signin_button"
                type="button"
              >
                Sign In
              </Button>
            )}
          </div>
        </div>
      </header>

      <div className="max-w-5xl mx-auto px-5 py-12">
        {/* Title */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-10"
        >
          <Badge className="mb-4 glass-sm border-primary/30 text-primary px-4 py-1 text-xs font-semibold uppercase tracking-wider">
            <BrainCircuit className="h-3 w-3 mr-1.5" />
            Generated by COGT + META + AUTN — Architecture Council
          </Badge>
          <p className="text-xs font-mono text-amber-400/60 mb-2">
            Charter v21{" "}
            <span className="text-white/30">(Ratified 2026-05-19)</span>
          </p>
          <h1 className="font-display font-black text-4xl md:text-5xl text-foreground mb-4 leading-tight">
            The EduAI
            <br />
            <span className="text-primary">Sovereign Vision</span>
          </h1>
          <p className="text-muted-foreground max-w-2xl leading-relaxed">
            This document surfaces the founding insight, technical architecture,
            and funding case for EduAI — generated by the platform’s own
            sovereign intelligence engines, not written by a marketer.
          </p>
        </motion.div>

        {/* Live stats strip — now sourced from VisionWithFunding + VisionStats */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.15 }}
          className="glass-lg rounded-2xl p-5 mb-10"
          data-ocid="vision.stats_strip"
        >
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            {statsLoading || fundingLoading
              ? [1, 2, 3, 4, 5].map((k) => (
                  <Skeleton key={k} className="h-14 rounded-xl" />
                ))
              : [
                  {
                    value:
                      totalStudents ??
                      (stats ? Number(stats.totalStudentsFlagged) : null),
                    label: "Students",
                    color: "oklch(0.78 0.22 200)",
                  },
                  {
                    value:
                      totalRecognitions ??
                      (stats ? Number(stats.achievementsSealed) : null),
                    label: "Recognitions",
                    color: "oklch(0.75 0.16 70)",
                  },
                  {
                    value: activePrograms,
                    label: "Active Programs",
                    color: "oklch(0.72 0.17 155)",
                  },
                  {
                    value: stats ? Number(stats.nominationsSent) : null,
                    label: "Nominations Sent",
                    color: "oklch(0.68 0.18 280)",
                  },
                  {
                    value:
                      fundingTargets.filter((t) => t.status === "Funded")
                        .length || null,
                    label: "Funded Initiatives",
                    color: "oklch(0.72 0.17 145)",
                  },
                ].map((s) => (
                  <div key={s.label} className="text-center">
                    <p
                      className="font-display font-black text-2xl"
                      style={{ color: s.color }}
                    >
                      {s.value !== null && s.value !== undefined
                        ? Number(s.value).toLocaleString()
                        : "—"}
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {s.label}
                    </p>
                  </div>
                ))}
          </div>
        </motion.div>

        <div className="grid md:grid-cols-[200px_1fr] gap-8">
          {/* Sticky section nav */}
          <aside className="hidden md:block">
            <div className="sticky top-20 glass rounded-2xl p-3 space-y-1">
              <p className="text-[10px] uppercase tracking-widest text-muted-foreground/50 px-2 mb-3 font-semibold">
                Sections
              </p>
              {NAV_SECTIONS.map((s) => {
                const Icon = s.icon;
                return (
                  <a
                    key={s.id}
                    href={s.anchor}
                    data-ocid={`vision.nav.${s.id}_link`}
                    className="flex items-center gap-2 rounded-xl px-3 py-2.5 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-white/5 transition-smooth"
                  >
                    <Icon className="h-3.5 w-3.5 shrink-0" />
                    {s.label}
                  </a>
                );
              })}
            </div>
          </aside>

          {/* Main content */}
          <div className="space-y-6">
            {/* Founder Story — canonical, always shown */}
            <FounderStorySection
              founderStory={founderStory}
              isLoading={docLoading && fundingLoading}
            />

            {/* Other vision sections */}
            {contentSections.map((s) => (
              <SectionBlock
                key={s.id}
                id={s.id}
                icon={s.icon}
                title={s.title}
                content={s.content}
                accentColor={s.color}
                isLoading={docLoading}
              />
            ))}

            {/* Funding Tracker — live from backend */}
            <FundingTracker
              targets={fundingTargets}
              isLoading={fundingLoading}
            />

            {/* Footer CTA */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="glass-lg rounded-2xl p-6 border border-primary/15 text-center"
            >
              <Star className="h-6 w-6 text-accent mx-auto mb-4" />
              <h3 className="font-display font-bold text-lg text-foreground mb-3">
                Experience the Platform
              </h3>
              <p className="text-sm text-muted-foreground mb-5">
                This is not a pitch. The intelligence that built this platform
                is waiting for you.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Button asChild data-ocid="vision.try_demo_button">
                  <Link to="/demo">Try Demo</Link>
                </Button>
                <Button
                  variant="outline"
                  asChild
                  data-ocid="vision.student_portal_button"
                >
                  <Link to="/dashboard">
                    <GraduationCap className="mr-1.5 h-4 w-4" />
                    Student Portal
                  </Link>
                </Button>
                <Button
                  variant="outline"
                  asChild
                  data-ocid="vision.engines_button"
                >
                  <Link to="/engines">
                    <Layers className="mr-1.5 h-4 w-4" />
                    Engine Registry
                  </Link>
                </Button>
              </div>
            </motion.div>

            {/* Sovereign laws ribbon */}
            <div
              className="glass-sm rounded-2xl px-5 py-4 flex flex-wrap gap-2"
              data-ocid="vision.laws_ribbon"
            >
              <p className="text-[10px] uppercase tracking-widest text-muted-foreground/50 font-semibold w-full mb-1">
                Governing Laws & Protocols
              </p>
              {[
                "LEX_SVRN",
                "LEX_MLTS",
                "LEX_FLOR",
                "LEX_INIT",
                "LEX_RNVT",
                "LEX_SPEC",
                "LEX_PRSN",
                "LEX_PONT",
                "LEX_RGST",
                "PRTL_UXIN",
                "PRTL_SSSC",
                "PRTL_ADXF",
                "PRTL_COHG",
                "PRTL_RCGN",
                "PRTL_TCHR",
                "PRTL_PRCP",
              ].map((law) => (
                <Badge
                  key={law}
                  variant="outline"
                  className="text-[10px] font-mono glass-sm border-primary/20 text-primary/70"
                >
                  {law}
                </Badge>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Charter v21 New Articles */}
      <section className="mt-12 border-t border-white/10 pt-12 max-w-5xl mx-auto px-5">
        <h2 className="text-white/40 font-mono text-xs tracking-widest uppercase mb-8">
          Charter v21 — New Articles
        </h2>
        <div className="space-y-8">
          <div className="glass border border-amber-500/20 rounded-xl p-6">
            <h3 className="text-amber-400 font-mono text-sm tracking-widest mb-4">
              ARTICLE VI — LANGUAGE BRIDGES (ENTANGLEMENTS)
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-xs font-mono">
                <thead>
                  <tr className="text-white/40 border-b border-white/10">
                    <th className="text-left py-2 pr-4">ID</th>
                    <th className="text-left py-2 pr-4">Substrates</th>
                    <th className="text-left py-2">Protocol</th>
                  </tr>
                </thead>
                <tbody className="text-white/70">
                  {[
                    [
                      "PONT",
                      "ICPM ↔ JLIA",
                      "Motoko→Julia math, FLOR both sides",
                    ],
                    ["MRDM", "ICPM ↔ EMRT", "State→memory, append-only"],
                    [
                      "AXON",
                      "EART → ICPM",
                      "Autonomous outputs inject into pipeline",
                    ],
                    [
                      "CRUX",
                      "JLIA → EMRT",
                      "FLOR values direct to memory zones",
                    ],
                    ["NXUS", "All → RGST", "Registry stats write-only"],
                  ].map(([id, sub, proto]) => (
                    <tr key={id} className="border-b border-white/5">
                      <td className="py-2 pr-4 text-amber-400">{id}</td>
                      <td className="py-2 pr-4">{sub}</td>
                      <td className="py-2 text-white/50">{proto}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
          <div className="glass border border-amber-500/20 rounded-xl p-6">
            <h3 className="text-amber-400 font-mono text-sm tracking-widest mb-4">
              ARTICLE VII — SILVER BUILDERS
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {[
                ["SVRN", "Sovereignty"],
                ["INTL", "Intelligence"],
                ["MMRY", "Memory"],
                ["KNOW", "Knowledge"],
                ["BRDG", "Bridges"],
                ["RGTM", "Registry"],
                ["AUTH", "Auth"],
                ["ANLX", "Analytics"],
              ].map(([id, domain]) => (
                <div
                  key={id}
                  className="glass border border-white/10 rounded-lg p-3"
                >
                  <p className="text-amber-400 font-mono text-sm">{id}</p>
                  <p className="text-white/50 text-xs mt-1">{domain}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="glass border border-amber-500/20 rounded-xl p-6">
            <h3 className="text-amber-400 font-mono text-sm tracking-widest mb-4">
              ARTICLE VIII — THE THREE FLOORS
            </h3>
            <div className="space-y-3">
              {[
                [
                  "FLOR",
                  "Fibonacci Integer Floor",
                  "compound_floor(n) = floor(n × PHI) → nearest F(k). All scores compound on Fibonacci integers.",
                ],
                [
                  "ZFLR",
                  "Zone Floor",
                  "Memory only moves: HOT→WARM→COLD→FROZEN→VAULT. Never backward.",
                ],
                [
                  "TFLR",
                  "Temporal Floor",
                  "All intervals are Fibonacci numbers only: 1,1,2,3,5,8,13,21,34,55...",
                ],
              ].map(([id, name, formula]) => (
                <div key={id} className="flex gap-4 p-3 rounded-lg bg-white/5">
                  <div className="shrink-0">
                    <span className="text-amber-400 font-mono text-sm">
                      {id}
                    </span>
                  </div>
                  <div>
                    <p className="text-white/70 text-xs font-medium">{name}</p>
                    <p className="text-white/40 text-xs mt-1 font-mono">
                      {formula}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Research & Theory */}
      <motion.section
        id="research"
        data-ocid="vision.research_section"
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="mt-16"
      >
        {/* Section heading */}
        <div className="glass rounded-2xl p-6 md:p-8 mb-6">
          <div className="flex items-center gap-3">
            <div
              className="h-10 w-10 rounded-xl flex items-center justify-center"
              style={{
                background: "rgba(255,185,0,0.12)",
                border: "1px solid rgba(255,185,0,0.30)",
              }}
            >
              <BookOpen
                className="h-5 w-5"
                style={{ color: "oklch(0.85 0.18 85)" }}
              />
            </div>
            <div>
              <h2 className="font-display font-black text-xl text-foreground">
                Research &amp; Theory
              </h2>
              <p className="text-xs text-muted-foreground mt-0.5">
                Sovereign intelligence papers generated by COGT+META+AUTN
              </p>
            </div>
          </div>
        </div>

        {/* Diego Protocol card */}
        <div className="glass rounded-2xl p-6 md:p-8">
          <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-4">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <span
                  className="text-xs font-semibold px-2 py-0.5 rounded-full"
                  style={{
                    background: "rgba(255,185,0,0.12)",
                    color: "oklch(0.85 0.18 85)",
                    border: "1px solid rgba(255,185,0,0.25)",
                  }}
                >
                  CASE STUDY
                </span>
                <span
                  className="text-xs font-semibold px-2 py-0.5 rounded-full"
                  style={{
                    background: "rgba(100,200,255,0.10)",
                    color: "oklch(0.78 0.14 210)",
                    border: "1px solid rgba(100,200,255,0.20)",
                  }}
                >
                  ACHV:DIEGO_001
                </span>
              </div>
              <h3 className="font-display font-black text-lg text-foreground">
                The Diego Protocol
              </h3>
              <p className="text-sm text-muted-foreground mt-1">
                Sovereign Intelligence-Driven Preparation for Non-Traditional
                Academic Competition in Under-Resourced Schools
              </p>
              <p className="text-xs text-muted-foreground/70 mt-2">
                Generated by COGT_v4 + META_v3 + AUTN_v2 · Sealed under
                LEX_SOVEREIGNUS · PRTL_RCGN + PRTL_SSSC + PRTL_ADXF
              </p>
            </div>
            <Button
              data-ocid="vision.diego_protocol_load_button"
              disabled={paperLoading}
              onClick={async () => {
                setPaperLoading(true);
                try {
                  // eslint-disable-next-line @typescript-eslint/no-explicit-any
                  const result = await (actor as any)?.getDiegoProtocol?.();
                  setPaperText(typeof result === "string" ? result : "");
                } catch {
                  setPaperText("");
                } finally {
                  setPaperLoading(false);
                }
              }}
              className="shrink-0 text-xs font-semibold"
              style={{
                background: "rgba(255,185,0,0.12)",
                color: "oklch(0.85 0.18 85)",
                border: "1px solid rgba(255,185,0,0.30)",
              }}
            >
              {paperLoading ? (
                <RefreshCw className="h-3.5 w-3.5 animate-spin mr-1.5" />
              ) : (
                <BookOpen className="h-3.5 w-3.5 mr-1.5" />
              )}
              {paperLoading ? "Loading…" : "Load Full Paper"}
            </Button>
          </div>

          {paperText && (
            <div
              data-ocid="vision.diego_protocol_paper"
              className="mt-4 rounded-xl p-4 max-h-96 overflow-y-auto"
              style={{
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.08)",
              }}
            >
              <pre className="text-xs text-muted-foreground whitespace-pre-wrap font-mono leading-relaxed">
                {paperText}
              </pre>
            </div>
          )}
        </div>
      </motion.section>

      {/* Footer */}
      <footer className="mt-16 border-t border-white/5 glass-xl py-6">
        <div className="max-w-5xl mx-auto px-5 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <GraduationCap className="h-4 w-4 text-primary" />
            <span className="font-display font-bold text-sm">
              Edu<span className="text-primary">AI</span>
            </span>
          </div>
          <p className="text-xs text-muted-foreground/50">
            © {new Date().getFullYear()}. Built with love using{" "}
            <a
              href={`https://caffeine.ai?utm_source=caffeine-footer&utm_medium=referral&utm_content=${encodeURIComponent(typeof window !== "undefined" ? window.location.hostname : "")}`}
              className="hover:text-muted-foreground transition-colors"
              target="_blank"
              rel="noopener noreferrer"
            >
              caffeine.ai
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
