import Map "mo:core/Map";
import Types "../types/curriculum";
import Char "mo:core/Char";
import List "mo:core/List";

module {
  public type SubjectStore = Map.Map<Text, Types.Subject>;
  public type TopicStore = Map.Map<Text, Types.Topic>;

  public func seedCurriculum(
    subjects : SubjectStore,
    topics : TopicStore,
  ) : () {
    // 12 subjects seeded per grade: K through 12
    let grades = ["K", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"];
    let subjectDefs : [(Text, Text)] = [
      ("ela",       "English Language Arts"),
      ("math",      "Mathematics"),
      ("science",   "Science"),
      ("socialstudies", "Social Studies"),
      ("geography", "Geography"),
      ("art",       "Art"),
      ("music",     "Music"),
      ("pe",        "Physical Education"),
      ("cs",        "Computer Science"),
      ("spanish",   "Foreign Language (Spanish)"),
      ("health",    "Health & Wellness"),
      ("electives", "Electives: Critical Thinking & Logic"),
    ];
    for (grade in grades.values()) {
      for ((subKey, subName) in subjectDefs.values()) {
        let subId = grade # "-" # subKey;
        subjects.add(subId, { id = subId; name = subName; gradeLevel = grade });
      };
    };

    // Topics per grade/subject — 3-5 TEKS-aligned topics each
    let topicData : [(Text, Text, Text)] = [
      // ── GRADE K ───────────────────────────────────────────────────────────
      ("K-ela-1", "K-ela", "Letter Recognition and Phonics"),
      ("K-ela-2", "K-ela", "Print Awareness"),
      ("K-ela-3", "K-ela", "Listening and Speaking"),
      ("K-math-1", "K-math", "Counting and Cardinality"),
      ("K-math-2", "K-math", "Shapes and Geometry"),
      ("K-math-3", "K-math", "Comparing Numbers"),
      ("K-science-1", "K-science", "Living and Non-Living Things"),
      ("K-science-2", "K-science", "Weather and Seasons"),
      ("K-science-3", "K-science", "Senses and Observation"),
      ("K-socialstudies-1", "K-socialstudies", "Self, Family, and Community"),
      ("K-socialstudies-2", "K-socialstudies", "Rules and Responsibilities"),
      ("K-socialstudies-3", "K-socialstudies", "Maps and Location"),
      ("K-geography-1", "K-geography", "Land and Water"),
      ("K-geography-2", "K-geography", "My Neighborhood and Community"),
      ("K-geography-3", "K-geography", "Directions and Maps"),
      ("K-art-1", "K-art", "Colors and Shapes in Art"),
      ("K-art-2", "K-art", "Drawing and Painting Basics"),
      ("K-art-3", "K-art", "Exploring Textures"),
      ("K-music-1", "K-music", "Rhythm and Beat"),
      ("K-music-2", "K-music", "Songs and Singing"),
      ("K-music-3", "K-music", "Listening and Movement"),
      ("K-pe-1", "K-pe", "Gross Motor Skills"),
      ("K-pe-2", "K-pe", "Simple Ball Games"),
      ("K-pe-3", "K-pe", "Body Awareness and Movement"),
      ("K-cs-1", "K-cs", "What is a Computer?"),
      ("K-cs-2", "K-cs", "Sequencing and Patterns"),
      ("K-cs-3", "K-cs", "Sorting and Grouping"),
      ("K-spanish-1", "K-spanish", "Colors and Numbers in Spanish"),
      ("K-spanish-2", "K-spanish", "Greetings and Introductions"),
      ("K-spanish-3", "K-spanish", "Family Words"),
      ("K-health-1", "K-health", "Healthy Foods and Nutrition"),
      ("K-health-2", "K-health", "Hygiene and Self-Care"),
      ("K-health-3", "K-health", "Feelings and Emotions"),
      ("K-electives-1", "K-electives", "Sorting and Classifying"),
      ("K-electives-2", "K-electives", "Patterns and Sequences"),
      ("K-electives-3", "K-electives", "Simple Puzzles and Problem Solving"),
      // ── GRADE 1 ───────────────────────────────────────────────────────────
      ("1-ela-1", "1-ela", "Decoding and Word Recognition"),
      ("1-ela-2", "1-ela", "Reading Comprehension"),
      ("1-ela-3", "1-ela", "Writing Sentences"),
      ("1-math-1", "1-math", "Addition and Subtraction Within 20"),
      ("1-math-2", "1-math", "Place Value"),
      ("1-math-3", "1-math", "Measurement and Data"),
      ("1-science-1", "1-science", "Properties of Matter"),
      ("1-science-2", "1-science", "Plant Life Cycles"),
      ("1-science-3", "1-science", "Earth and Sky"),
      ("1-socialstudies-1", "1-socialstudies", "Needs and Wants"),
      ("1-socialstudies-2", "1-socialstudies", "Citizenship and Community Helpers"),
      ("1-socialstudies-3", "1-socialstudies", "Past and Present"),
      ("1-geography-1", "1-geography", "Continents and Oceans"),
      ("1-geography-2", "1-geography", "Physical Features"),
      ("1-geography-3", "1-geography", "Map Keys and Symbols"),
      ("1-art-1", "1-art", "Primary and Secondary Colors"),
      ("1-art-2", "1-art", "Line and Shape"),
      ("1-art-3", "1-art", "Simple Printmaking"),
      ("1-music-1", "1-music", "Fast and Slow Tempo"),
      ("1-music-2", "1-music", "High and Low Pitch"),
      ("1-music-3", "1-music", "Musical Instruments Introduction"),
      ("1-pe-1", "1-pe", "Running and Jumping"),
      ("1-pe-2", "1-pe", "Throwing and Catching"),
      ("1-pe-3", "1-pe", "Cooperative Play"),
      ("1-cs-1", "1-cs", "Algorithms as Step-by-Step Instructions"),
      ("1-cs-2", "1-cs", "Input and Output"),
      ("1-cs-3", "1-cs", "Debugging: Finding Mistakes"),
      ("1-spanish-1", "1-spanish", "Animals in Spanish"),
      ("1-spanish-2", "1-spanish", "Days of the Week"),
      ("1-spanish-3", "1-spanish", "Classroom Objects"),
      ("1-health-1", "1-health", "Food Groups and Healthy Choices"),
      ("1-health-2", "1-health", "Exercise and Sleep"),
      ("1-health-3", "1-health", "Personal Safety"),
      ("1-electives-1", "1-electives", "Logic Puzzles"),
      ("1-electives-2", "1-electives", "Comparing and Ordering"),
      ("1-electives-3", "1-electives", "Creative Thinking Challenges"),
      // ── GRADE 2 ───────────────────────────────────────────────────────────
      ("2-ela-1", "2-ela", "Fluency and Vocabulary"),
      ("2-ela-2", "2-ela", "Main Idea and Details"),
      ("2-ela-3", "2-ela", "Writing Paragraphs"),
      ("2-math-1", "2-math", "Addition and Subtraction Within 1000"),
      ("2-math-2", "2-math", "Multiplication Introduction"),
      ("2-math-3", "2-math", "Fractions and Time"),
      ("2-science-1", "2-science", "States of Matter"),
      ("2-science-2", "2-science", "Animal Adaptations"),
      ("2-science-3", "2-science", "Soil and Rocks"),
      ("2-socialstudies-1", "2-socialstudies", "Texas Communities"),
      ("2-socialstudies-2", "2-socialstudies", "Economics and Trade"),
      ("2-socialstudies-3", "2-socialstudies", "Landforms and Geography"),
      ("2-geography-1", "2-geography", "Climate Zones"),
      ("2-geography-2", "2-geography", "Using a Globe"),
      ("2-geography-3", "2-geography", "Urban and Rural Areas"),
      ("2-art-1", "2-art", "Color Mixing"),
      ("2-art-2", "2-art", "Sculpture and 3D Forms"),
      ("2-art-3", "2-art", "Art from Around the World"),
      ("2-music-1", "2-music", "Quarter Notes and Rests"),
      ("2-music-2", "2-music", "Simple Melodies"),
      ("2-music-3", "2-music", "Music from Other Cultures"),
      ("2-pe-1", "2-pe", "Kicking and Striking"),
      ("2-pe-2", "2-pe", "Balance and Coordination"),
      ("2-pe-3", "2-pe", "Team Sports Introduction"),
      ("2-cs-1", "2-cs", "Loops and Repetition"),
      ("2-cs-2", "2-cs", "Data and Patterns"),
      ("2-cs-3", "2-cs", "Basic Conditionals"),
      ("2-spanish-1", "2-spanish", "Food and Drinks in Spanish"),
      ("2-spanish-2", "2-spanish", "Months and Seasons"),
      ("2-spanish-3", "2-spanish", "Colors and Adjectives"),
      ("2-health-1", "2-health", "Dental Health"),
      ("2-health-2", "2-health", "Germs and Hand Washing"),
      ("2-health-3", "2-health", "Conflict Resolution"),
      ("2-electives-1", "2-electives", "Basic Strategy Games"),
      ("2-electives-2", "2-electives", "Venn Diagrams"),
      ("2-electives-3", "2-electives", "Story Problems"),
      // ── GRADE 3 ───────────────────────────────────────────────────────────
      ("3-ela-1", "3-ela", "Reading Fiction and Nonfiction"),
      ("3-ela-2", "3-ela", "Text Structure and Author's Purpose"),
      ("3-ela-3", "3-ela", "Narrative Writing"),
      ("3-ela-4", "3-ela", "Grammar and Mechanics"),
      ("3-math-1", "3-math", "Multiplication and Division"),
      ("3-math-2", "3-math", "Fractions"),
      ("3-math-3", "3-math", "Area and Perimeter"),
      ("3-math-4", "3-math", "Patterns and Algebra"),
      ("3-science-1", "3-science", "Force and Motion"),
      ("3-science-2", "3-science", "Ecosystems"),
      ("3-science-3", "3-science", "Water Cycle"),
      ("3-socialstudies-1", "3-socialstudies", "Texas History and Geography"),
      ("3-socialstudies-2", "3-socialstudies", "Government and Citizenship"),
      ("3-socialstudies-3", "3-socialstudies", "Economics Basics"),
      ("3-geography-1", "3-geography", "Texas Regions and Landforms"),
      ("3-geography-2", "3-geography", "Natural Resources"),
      ("3-geography-3", "3-geography", "Reading Maps and Scales"),
      ("3-art-1", "3-art", "Elements of Art"),
      ("3-art-2", "3-art", "Art History: Ancient to Medieval"),
      ("3-art-3", "3-art", "Watercolor and Mixed Media"),
      ("3-music-1", "3-music", "Musical Notation Basics"),
      ("3-music-2", "3-music", "Singing in Parts"),
      ("3-music-3", "3-music", "Instrument Families"),
      ("3-pe-1", "3-pe", "Cardiovascular Fitness"),
      ("3-pe-2", "3-pe", "Volleyball and Net Sports"),
      ("3-pe-3", "3-pe", "Flexibility and Stretching"),
      ("3-cs-1", "3-cs", "Functions and Procedures"),
      ("3-cs-2", "3-cs", "Events and Interactivity"),
      ("3-cs-3", "3-cs", "Binary and Data Representation"),
      ("3-spanish-1", "3-spanish", "Weather Expressions"),
      ("3-spanish-2", "3-spanish", "Telling Time"),
      ("3-spanish-3", "3-spanish", "Shopping and Prices"),
      ("3-health-1", "3-health", "Substance Awareness"),
      ("3-health-2", "3-health", "Sun Safety and Skin Care"),
      ("3-health-3", "3-health", "Making Healthy Decisions"),
      ("3-electives-1", "3-electives", "Grid Logic Puzzles"),
      ("3-electives-2", "3-electives", "Introduction to Debate"),
      ("3-electives-3", "3-electives", "Math Enrichment Challenges"),
      // ── GRADE 4 ───────────────────────────────────────────────────────────
      ("4-ela-1", "4-ela", "Literary Elements"),
      ("4-ela-2", "4-ela", "Informational Texts"),
      ("4-ela-3", "4-ela", "Expository Writing"),
      ("4-ela-4", "4-ela", "Research Skills"),
      ("4-math-1", "4-math", "Multi-Digit Multiplication"),
      ("4-math-2", "4-math", "Decimals and Fractions"),
      ("4-math-3", "4-math", "Geometry"),
      ("4-math-4", "4-math", "Data Analysis"),
      ("4-science-1", "4-science", "Energy Forms and Transfer"),
      ("4-science-2", "4-science", "Earth's Layers"),
      ("4-science-3", "4-science", "Food Chains"),
      ("4-socialstudies-1", "4-socialstudies", "Texas in the Nation"),
      ("4-socialstudies-2", "4-socialstudies", "Native American Cultures"),
      ("4-socialstudies-3", "4-socialstudies", "Texas Economy and Resources"),
      ("4-geography-1", "4-geography", "US Regions"),
      ("4-geography-2", "4-geography", "Human Migration"),
      ("4-geography-3", "4-geography", "Environmental Issues"),
      ("4-art-1", "4-art", "Perspective Drawing"),
      ("4-art-2", "4-art", "Portrait and Self-Portrait"),
      ("4-art-3", "4-art", "American Art History"),
      ("4-music-1", "4-music", "Reading Sheet Music"),
      ("4-music-2", "4-music", "Harmony and Chords"),
      ("4-music-3", "4-music", "Composer Study"),
      ("4-pe-1", "4-pe", "Soccer and Field Sports"),
      ("4-pe-2", "4-pe", "Track and Field Basics"),
      ("4-pe-3", "4-pe", "Goal Setting and Fitness"),
      ("4-cs-1", "4-cs", "Variables and Data Types"),
      ("4-cs-2", "4-cs", "Nested Loops"),
      ("4-cs-3", "4-cs", "Web Basics: HTML Introduction"),
      ("4-spanish-1", "4-spanish", "Transportation Vocabulary"),
      ("4-spanish-2", "4-spanish", "Describing People"),
      ("4-spanish-3", "4-spanish", "My School and Schedule"),
      ("4-health-1", "4-health", "Mental Health Awareness"),
      ("4-health-2", "4-health", "Puberty and Growing Up"),
      ("4-health-3", "4-health", "Community Health Resources"),
      ("4-electives-1", "4-electives", "Logic Trees and Decision Making"),
      ("4-electives-2", "4-electives", "Chess Strategy Basics"),
      ("4-electives-3", "4-electives", "Lateral Thinking Puzzles"),
      // ── GRADE 5 ───────────────────────────────────────────────────────────
      ("5-ela-1", "5-ela", "Theme and Figurative Language"),
      ("5-ela-2", "5-ela", "Point of View and Bias"),
      ("5-ela-3", "5-ela", "Persuasive Writing"),
      ("5-ela-4", "5-ela", "Vocabulary and Context Clues"),
      ("5-math-1", "5-math", "Decimals Operations"),
      ("5-math-2", "5-math", "Fractions Operations"),
      ("5-math-3", "5-math", "Volume and Coordinate Plane"),
      ("5-math-4", "5-math", "Algebraic Thinking"),
      ("5-science-1", "5-science", "Matter and Chemical Changes"),
      ("5-science-2", "5-science", "Earth Systems and Cycles"),
      ("5-science-3", "5-science", "Space and Solar System"),
      ("5-socialstudies-1", "5-socialstudies", "US History to 1865"),
      ("5-socialstudies-2", "5-socialstudies", "US Geography"),
      ("5-socialstudies-3", "5-socialstudies", "Branches of Government"),
      ("5-geography-1", "5-geography", "World Rivers and Mountains"),
      ("5-geography-2", "5-geography", "Time Zones"),
      ("5-geography-3", "5-geography", "Country and Capital Study"),
      ("5-art-1", "5-art", "Painting Techniques"),
      ("5-art-2", "5-art", "Digital Art Basics"),
      ("5-art-3", "5-art", "Art Critique and Analysis"),
      ("5-music-1", "5-music", "Scales and Keys"),
      ("5-music-2", "5-music", "Music Genres Survey"),
      ("5-music-3", "5-music", "Performance and Stage Presence"),
      ("5-pe-1", "5-pe", "Basketball and Court Sports"),
      ("5-pe-2", "5-pe", "Fitness Testing and Goals"),
      ("5-pe-3", "5-pe", "Sportsmanship and Teamwork"),
      ("5-cs-1", "5-cs", "Introduction to Programming Logic"),
      ("5-cs-2", "5-cs", "Spreadsheets and Data"),
      ("5-cs-3", "5-cs", "Digital Citizenship and Safety"),
      ("5-spanish-1", "5-spanish", "Past Tense Verbs"),
      ("5-spanish-2", "5-spanish", "Hobbies and Free Time"),
      ("5-spanish-3", "5-spanish", "Spanish-Speaking Countries"),
      ("5-health-1", "5-health", "First Aid Basics"),
      ("5-health-2", "5-health", "Disease Prevention"),
      ("5-health-3", "5-health", "Stress Management"),
      ("5-electives-1", "5-electives", "Socratic Questioning"),
      ("5-electives-2", "5-electives", "Visual Logic and Spatial Reasoning"),
      ("5-electives-3", "5-electives", "Math Competition Prep"),
      // ── GRADE 6 ───────────────────────────────────────────────────────────
      ("6-ela-1", "6-ela", "Literary Analysis"),
      ("6-ela-2", "6-ela", "Argumentative Writing"),
      ("6-ela-3", "6-ela", "Media Literacy"),
      ("6-math-1", "6-math", "Ratios and Proportions"),
      ("6-math-2", "6-math", "Integers and Number Sense"),
      ("6-math-3", "6-math", "Expressions and Equations"),
      ("6-math-4", "6-math", "Statistics"),
      ("6-science-1", "6-science", "Cells and Organisms"),
      ("6-science-2", "6-science", "Plate Tectonics"),
      ("6-science-3", "6-science", "Astronomy"),
      ("6-socialstudies-1", "6-socialstudies", "Ancient World History"),
      ("6-socialstudies-2", "6-socialstudies", "World Cultures"),
      ("6-socialstudies-3", "6-socialstudies", "Geography of World Regions"),
      ("6-geography-1", "6-geography", "Physical and Political Maps"),
      ("6-geography-2", "6-geography", "Population and Demographics"),
      ("6-geography-3", "6-geography", "Economic Geography"),
      ("6-art-1", "6-art", "Art of the Ancient World"),
      ("6-art-2", "6-art", "Pattern and Design"),
      ("6-art-3", "6-art", "Photography Basics"),
      ("6-music-1", "6-music", "Music Theory Fundamentals"),
      ("6-music-2", "6-music", "World Music Survey"),
      ("6-music-3", "6-music", "Ensemble Playing"),
      ("6-pe-1", "6-pe", "Aerobic and Anaerobic Exercise"),
      ("6-pe-2", "6-pe", "Flag Football"),
      ("6-pe-3", "6-pe", "Health-Related Fitness Components"),
      ("6-cs-1", "6-cs", "Python Basics"),
      ("6-cs-2", "6-cs", "Conditionals and Loops in Code"),
      ("6-cs-3", "6-cs", "Cybersecurity Awareness"),
      ("6-spanish-1", "6-spanish", "Irregular Verbs"),
      ("6-spanish-2", "6-spanish", "Travel and Directions"),
      ("6-spanish-3", "6-spanish", "Hispanic Culture and Traditions"),
      ("6-health-1", "6-health", "Nutrition Labels and Healthy Eating"),
      ("6-health-2", "6-health", "Body Systems Overview"),
      ("6-health-3", "6-health", "Online Safety and Privacy"),
      ("6-electives-1", "6-electives", "Argument Mapping"),
      ("6-electives-2", "6-electives", "Introduction to Formal Logic"),
      ("6-electives-3", "6-electives", "Critical Reading Strategies"),
      // ── GRADE 7 ───────────────────────────────────────────────────────────
      ("7-ela-1", "7-ela", "Complex Texts and Synthesis"),
      ("7-ela-2", "7-ela", "Research-Based Writing"),
      ("7-ela-3", "7-ela", "Grammar and Style"),
      ("7-math-1", "7-math", "Proportional Relationships"),
      ("7-math-2", "7-math", "Percent and Financial Literacy"),
      ("7-math-3", "7-math", "Geometry: Similarity and Scale"),
      ("7-math-4", "7-math", "Probability"),
      ("7-science-1", "7-science", "Genetics and Heredity"),
      ("7-science-2", "7-science", "Evolution and Natural Selection"),
      ("7-science-3", "7-science", "Chemical Reactions"),
      ("7-socialstudies-1", "7-socialstudies", "Texas History 1800s-Present"),
      ("7-socialstudies-2", "7-socialstudies", "Texas Government"),
      ("7-socialstudies-3", "7-socialstudies", "Texas Economics"),
      ("7-geography-1", "7-geography", "Latin America: Physical and Cultural"),
      ("7-geography-2", "7-geography", "Africa: Physical and Cultural"),
      ("7-geography-3", "7-geography", "Asia: Physical and Cultural"),
      ("7-art-1", "7-art", "Design Principles"),
      ("7-art-2", "7-art", "Ceramics and Sculpture"),
      ("7-art-3", "7-art", "Graphic Design Basics"),
      ("7-music-1", "7-music", "Rhythm and Meter"),
      ("7-music-2", "7-music", "Jazz and Blues History"),
      ("7-music-3", "7-music", "Songwriting Basics"),
      ("7-pe-1", "7-pe", "Weight Training Introduction"),
      ("7-pe-2", "7-pe", "Tennis and Racquet Sports"),
      ("7-pe-3", "7-pe", "Personal Fitness Planning"),
      ("7-cs-1", "7-cs", "Functions and Scope"),
      ("7-cs-2", "7-cs", "Lists and Arrays"),
      ("7-cs-3", "7-cs", "Game Design Basics"),
      ("7-spanish-1", "7-spanish", "Future Tense"),
      ("7-spanish-2", "7-spanish", "Subjunctive Mood Introduction"),
      ("7-spanish-3", "7-spanish", "Literature in Spanish"),
      ("7-health-1", "7-health", "Reproductive Health Basics"),
      ("7-health-2", "7-health", "Alcohol and Tobacco Awareness"),
      ("7-health-3", "7-health", "Social Media and Mental Health"),
      ("7-electives-1", "7-electives", "Logical Fallacies"),
      ("7-electives-2", "7-electives", "Introduction to Philosophy"),
      ("7-electives-3", "7-electives", "Critical Thinking in Media"),
      // ── GRADE 8 ───────────────────────────────────────────────────────────
      ("8-ela-1", "8-ela", "Analyzing Multiple Texts"),
      ("8-ela-2", "8-ela", "Expository and Argumentative Writing"),
      ("8-ela-3", "8-ela", "Vocabulary: Roots and Affixes"),
      ("8-math-1", "8-math", "Linear Equations"),
      ("8-math-2", "8-math", "Systems of Equations"),
      ("8-math-3", "8-math", "Pythagorean Theorem"),
      ("8-math-4", "8-math", "Functions"),
      ("8-science-1", "8-science", "Force, Motion, and Energy"),
      ("8-science-2", "8-science", "Waves and Light"),
      ("8-science-3", "8-science", "Earth's History"),
      ("8-socialstudies-1", "8-socialstudies", "US History 1877-Present"),
      ("8-socialstudies-2", "8-socialstudies", "Civil Rights and Social Movements"),
      ("8-socialstudies-3", "8-socialstudies", "US Government and Constitution"),
      ("8-geography-1", "8-geography", "Europe: Physical and Political"),
      ("8-geography-2", "8-geography", "Middle East: Conflict and Resources"),
      ("8-geography-3", "8-geography", "Globalization and Trade Routes"),
      ("8-art-1", "8-art", "20th Century Art Movements"),
      ("8-art-2", "8-art", "Digital Illustration"),
      ("8-art-3", "8-art", "Portfolio Development"),
      ("8-music-1", "8-music", "Music Production Basics"),
      ("8-music-2", "8-music", "Rock and Pop History"),
      ("8-music-3", "8-music", "Advanced Ensemble"),
      ("8-pe-1", "8-pe", "Endurance Training"),
      ("8-pe-2", "8-pe", "Self-Defense and Martial Arts Basics"),
      ("8-pe-3", "8-pe", "Sports Officiating and Rules"),
      ("8-cs-1", "8-cs", "Object-Oriented Concepts"),
      ("8-cs-2", "8-cs", "Databases and SQL Basics"),
      ("8-cs-3", "8-cs", "App Prototyping"),
      ("8-spanish-1", "8-spanish", "Conditional Tense"),
      ("8-spanish-2", "8-spanish", "Current Events in Spanish"),
      ("8-spanish-3", "8-spanish", "Advanced Conversation"),
      ("8-health-1", "8-health", "Drug Awareness and Prevention"),
      ("8-health-2", "8-health", "Healthy Relationships"),
      ("8-health-3", "8-health", "Career and Life Planning"),
      ("8-electives-1", "8-electives", "Formal Proofs and Arguments"),
      ("8-electives-2", "8-electives", "Ethics and Decision Frameworks"),
      ("8-electives-3", "8-electives", "Statistical Thinking"),
      // ── GRADE 9 ───────────────────────────────────────────────────────────
      ("9-ela-1", "9-ela", "World Literature"),
      ("9-ela-2", "9-ela", "Analytical Writing"),
      ("9-ela-3", "9-ela", "Rhetoric and Persuasion"),
      ("9-math-1", "9-math", "Linear Functions and Equations"),
      ("9-math-2", "9-math", "Quadratic Functions"),
      ("9-math-3", "9-math", "Systems of Equations"),
      ("9-math-4", "9-math", "Statistics and Probability"),
      ("9-science-1", "9-science", "Cell Biology"),
      ("9-science-2", "9-science", "Genetics and Biotechnology"),
      ("9-science-3", "9-science", "Ecology and Biomes"),
      ("9-socialstudies-1", "9-socialstudies", "Physical Geography"),
      ("9-socialstudies-2", "9-socialstudies", "Cultural Geography"),
      ("9-socialstudies-3", "9-socialstudies", "Human-Environment Interaction"),
      ("9-geography-1", "9-geography", "Mapping the World's Resources"),
      ("9-geography-2", "9-geography", "Urban Geography"),
      ("9-geography-3", "9-geography", "Climate Change and Geography"),
      ("9-art-1", "9-art", "Studio Art: Drawing"),
      ("9-art-2", "9-art", "Color Theory Advanced"),
      ("9-art-3", "9-art", "Art and Technology"),
      ("9-music-1", "9-music", "Music Theory: Intermediate"),
      ("9-music-2", "9-music", "Classical Music History"),
      ("9-music-3", "9-music", "Performance Techniques"),
      ("9-pe-1", "9-pe", "Individual Sports: Swimming and Golf"),
      ("9-pe-2", "9-pe", "Lifetime Fitness Concepts"),
      ("9-pe-3", "9-pe", "Sports Nutrition"),
      ("9-cs-1", "9-cs", "Algorithms and Complexity"),
      ("9-cs-2", "9-cs", "Web Development: HTML and CSS"),
      ("9-cs-3", "9-cs", "Networks and the Internet"),
      ("9-spanish-1", "9-spanish", "AP Spanish Introduction"),
      ("9-spanish-2", "9-spanish", "Spanish Literature Survey"),
      ("9-spanish-3", "9-spanish", "Oral Proficiency"),
      ("9-health-1", "9-health", "Human Anatomy Basics"),
      ("9-health-2", "9-health", "Reproductive Health"),
      ("9-health-3", "9-health", "Consumer Health"),
      ("9-electives-1", "9-electives", "Deductive and Inductive Reasoning"),
      ("9-electives-2", "9-electives", "Introduction to Epistemology"),
      ("9-electives-3", "9-electives", "Research Methods"),
      // ── GRADE 10 ──────────────────────────────────────────────────────────
      ("10-ela-1", "10-ela", "British and World Literature"),
      ("10-ela-2", "10-ela", "Literary Criticism"),
      ("10-ela-3", "10-ela", "Research and Documentation"),
      ("10-math-1", "10-math", "Triangles and Proofs"),
      ("10-math-2", "10-math", "Circles and Polygons"),
      ("10-math-3", "10-math", "Transformations"),
      ("10-math-4", "10-math", "Coordinate Geometry"),
      ("10-science-1", "10-science", "Atomic Structure"),
      ("10-science-2", "10-science", "Chemical Bonding"),
      ("10-science-3", "10-science", "Stoichiometry"),
      ("10-socialstudies-1", "10-socialstudies", "Ancient Civilizations"),
      ("10-socialstudies-2", "10-socialstudies", "Renaissance to Industrial Revolution"),
      ("10-socialstudies-3", "10-socialstudies", "20th Century World Events"),
      ("10-geography-1", "10-geography", "Geopolitics and Borders"),
      ("10-geography-2", "10-geography", "Environmental Policy"),
      ("10-geography-3", "10-geography", "Global Resource Distribution"),
      ("10-art-1", "10-art", "Painting: Oils and Acrylics"),
      ("10-art-2", "10-art", "Contemporary Art Movements"),
      ("10-art-3", "10-art", "Independent Studio Project"),
      ("10-music-1", "10-music", "Music Theory: Advanced Harmony"),
      ("10-music-2", "10-music", "Electronic Music Production"),
      ("10-music-3", "10-music", "Music Business Basics"),
      ("10-pe-1", "10-pe", "Advanced Weight Training"),
      ("10-pe-2", "10-pe", "Leadership in Team Sports"),
      ("10-pe-3", "10-pe", "Wellness and Stress Reduction"),
      ("10-cs-1", "10-cs", "JavaScript and Web Interactivity"),
      ("10-cs-2", "10-cs", "Data Structures Basics"),
      ("10-cs-3", "10-cs", "AI and Machine Learning Overview"),
      ("10-spanish-1", "10-spanish", "AP Spanish Language"),
      ("10-spanish-2", "10-spanish", "Grammar Mastery"),
      ("10-spanish-3", "10-spanish", "Hispanic Literature"),
      ("10-health-1", "10-health", "Chronic Disease Prevention"),
      ("10-health-2", "10-health", "Mental Health Disorders and Support"),
      ("10-health-3", "10-health", "Community Health Advocacy"),
      ("10-electives-1", "10-electives", "Philosophy of Science"),
      ("10-electives-2", "10-electives", "Advanced Debate"),
      ("10-electives-3", "10-electives", "Mathematical Logic"),
      // ── GRADE 11 ──────────────────────────────────────────────────────────
      ("11-ela-1", "11-ela", "American Literature"),
      ("11-ela-2", "11-ela", "Seminal US Texts"),
      ("11-ela-3", "11-ela", "College-Ready Writing"),
      ("11-math-1", "11-math", "Polynomials and Rational Functions"),
      ("11-math-2", "11-math", "Exponential and Logarithmic Functions"),
      ("11-math-3", "11-math", "Trigonometry"),
      ("11-math-4", "11-math", "Sequences and Series"),
      ("11-science-1", "11-science", "Kinematics and Dynamics"),
      ("11-science-2", "11-science", "Energy and Thermodynamics"),
      ("11-science-3", "11-science", "Electricity and Magnetism"),
      ("11-socialstudies-1", "11-socialstudies", "Founding of the Nation"),
      ("11-socialstudies-2", "11-socialstudies", "Civil War and Reconstruction"),
      ("11-socialstudies-3", "11-socialstudies", "America in the 20th Century"),
      ("11-geography-1", "11-geography", "Advanced Cartography"),
      ("11-geography-2", "11-geography", "Comparative Political Systems"),
      ("11-geography-3", "11-geography", "Global Development Issues"),
      ("11-art-1", "11-art", "Art Portfolio and Exhibition"),
      ("11-art-2", "11-art", "Art and Social Commentary"),
      ("11-art-3", "11-art", "Advanced Photography"),
      ("11-music-1", "11-music", "AP Music Theory"),
      ("11-music-2", "11-music", "Original Composition"),
      ("11-music-3", "11-music", "Music Technology and DAW"),
      ("11-pe-1", "11-pe", "Lifetime Sports"),
      ("11-pe-2", "11-pe", "Peer Coaching and Leadership"),
      ("11-pe-3", "11-pe", "Sports Medicine Basics"),
      ("11-cs-1", "11-cs", "Algorithms and Problem Solving"),
      ("11-cs-2", "11-cs", "Cybersecurity Deep Dive"),
      ("11-cs-3", "11-cs", "Software Development Lifecycle"),
      ("11-spanish-1", "11-spanish", "AP Spanish Literature"),
      ("11-spanish-2", "11-spanish", "Advanced Writing in Spanish"),
      ("11-spanish-3", "11-spanish", "Latin American Literature"),
      ("11-health-1", "11-health", "First Responder Basics"),
      ("11-health-2", "11-health", "Pharmacology Awareness"),
      ("11-health-3", "11-health", "Public Health and Epidemiology"),
      ("11-electives-1", "11-electives", "Formal Systems and Proof"),
      ("11-electives-2", "11-electives", "Ethical Reasoning"),
      ("11-electives-3", "11-electives", "Competitive Math"),
      // ── GRADE 12 ──────────────────────────────────────────────────────────
      ("12-ela-1", "12-ela", "Senior Seminar and Research"),
      ("12-ela-2", "12-ela", "Contemporary Literature"),
      ("12-ela-3", "12-ela", "Career and College Writing"),
      ("12-math-1", "12-math", "Limits and Derivatives"),
      ("12-math-2", "12-math", "Statistical Inference"),
      ("12-math-3", "12-math", "Financial Mathematics"),
      ("12-science-1", "12-science", "Ecosystems and Biodiversity"),
      ("12-science-2", "12-science", "Climate and Human Impact"),
      ("12-science-3", "12-science", "Sustainability and Resources"),
      ("12-socialstudies-1", "12-socialstudies", "US Government and Civic Participation"),
      ("12-socialstudies-2", "12-socialstudies", "Macroeconomics"),
      ("12-socialstudies-3", "12-socialstudies", "Personal Finance"),
      ("12-geography-1", "12-geography", "Global Geopolitics and Future Trends"),
      ("12-geography-2", "12-geography", "Sustainable Development Goals"),
      ("12-geography-3", "12-geography", "Independent Geography Research"),
      ("12-art-1", "12-art", "Senior Art Exhibition"),
      ("12-art-2", "12-art", "Art Career Pathways"),
      ("12-art-3", "12-art", "Art History Capstone"),
      ("12-music-1", "12-music", "Senior Recital Preparation"),
      ("12-music-2", "12-music", "Music Theory Capstone"),
      ("12-music-3", "12-music", "Music Industry and Careers"),
      ("12-pe-1", "12-pe", "Senior Fitness Capstone"),
      ("12-pe-2", "12-pe", "Sports and Recreation Leadership"),
      ("12-pe-3", "12-pe", "Health for Life"),
      ("12-cs-1", "12-cs", "Capstone Software Project"),
      ("12-cs-2", "12-cs", "Cloud Computing Basics"),
      ("12-cs-3", "12-cs", "Ethics in Technology"),
      ("12-spanish-1", "12-spanish", "AP Spanish Capstone"),
      ("12-spanish-2", "12-spanish", "Spanish Film and Media"),
      ("12-spanish-3", "12-spanish", "Independent Research in Spanish"),
      ("12-health-1", "12-health", "Adult Health Transitions"),
      ("12-health-2", "12-health", "Global Health Issues"),
      ("12-health-3", "12-health", "Health Capstone Project"),
      ("12-electives-1", "12-electives", "Philosophy Capstone"),
      ("12-electives-2", "12-electives", "Independent Research Project"),
      ("12-electives-3", "12-electives", "Senior Logic and Problem Solving"),
    ];
    for ((topicId, subjectId, title) in topicData.values()) {
      let gradeLevel = if (subjectId.size() > 0) {
        var g = "";
        label lp for (c in subjectId.chars()) {
          if (c == '-') { break lp };
          g #= ("" # c.toText());
        }; // lp
        g;
      } else { "" };
      topics.add(topicId, {
        id = topicId;
        subjectId = subjectId;
        title = title;
        description = title # " — TEKS-aligned topic for grade " # gradeLevel;
        gradeLevel = gradeLevel;
      });
    };
  };

  // getAllSubjects — returns one Subject record per unique subject type (12 unique subjects),
  // using the grade-K record for each. Used by Dashboard for logged-out users.
  public func getAllSubjects(subjects : SubjectStore) : [Types.Subject] {
    let seen = List.empty<Text>();
    let buf = List.empty<Types.Subject>();
    for ((_, s) in subjects.entries()) {
      // Derive subject key: everything after the first "-" in the id (e.g. "K-math" → "math")
      var subKey = "";
      var pastDash = false;
      for (c in s.id.chars()) {
        if (pastDash) {
          subKey #= c.toText();
        } else if (c == '-') {
          pastDash := true;
        };
      };
      if (not seen.any(func(k) { k == subKey })) {
        seen.add(subKey);
        buf.add(s);
      };
    };
    buf.toArray()
  };

  public func getSubjectsByGrade(
    subjects : SubjectStore,
    gradeLevel : Text,
  ) : [Types.Subject] {
    // When gradeLevel is empty, return all 12 unique subjects (one per type)
    if (gradeLevel.size() == 0) {
      return getAllSubjects(subjects);
    };
    let buf = List.empty<Types.Subject>();
    for ((_, s) in subjects.entries()) {
      if (s.gradeLevel == gradeLevel) {
        buf.add(s);
      };
    };
    buf.toArray();
  };

  public func getTopicsBySubject(
    topics : TopicStore,
    subjectId : Text,
  ) : [Types.Topic] {
    let buf = List.empty<Types.Topic>();
    for ((_, t) in topics.entries()) {
      if (t.subjectId == subjectId) {
        buf.add(t);
      };
    };
    buf.toArray();
  };
};
