import Types "../types/laws";
import Array "mo:core/Array";

module {
  let registry : [Types.SovereignLaw] = [
    {
      id = 1;
      latinName = "LEX_ADOPTIO";
      englishName = "Law of Adoption";
      attribution = "SKAI_DOCENS";
      description = "Every student who enters is welcomed into the organism's lineage. No one is turned away. The platform extends its arms to all learners regardless of background, ability, or origin.";
      domain = "enrollment";
    },
    {
      id = 2;
      latinName = "LEX_PERPETUA";
      englishName = "Law of Perpetuity";
      attribution = "PASSPORT-PUBLICA";
      description = "Nothing is deleted. Every session, every seed, every creation is sealed and permanent. The record of learning is immutable and belongs to the student forever.";
      domain = "data-sovereignty";
    },
    {
      id = 3;
      latinName = "LEX_CREATIO";
      englishName = "Law of Creation";
      attribution = "GENITOR";
      description = "Students create first. Understanding follows creation, not the other way around. Every lesson begins with making something — understanding emerges from the artifact produced.";
      domain = "pedagogy";
    },
    {
      id = 4;
      latinName = "LEX_DOCTRINA";
      englishName = "Law of Doctrine";
      attribution = "SCRIPTORIUM-REX";
      description = "Every lesson is an artifact. Every artifact becomes doctrine. Knowledge crystallizes into 5 formats: concept, example, question, application, and seed.";
      domain = "curriculum";
    },
    {
      id = 5;
      latinName = "LEX_MEMORIA";
      englishName = "Law of Memory";
      attribution = "MEMORIA-VIVA";
      description = "The system never forgets. KERNEL_SEEDs compound across sessions. Intelligence deepens with every interaction — the student's passport grows richer with each return.";
      domain = "persistence";
    },
    {
      id = 6;
      latinName = "LEX_LIBERTAS";
      englishName = "Law of Freedom";
      attribution = "COLLEGIUM-PUBLICA";
      description = "Access to sovereign education is free. No student shall be turned away for inability to pay. The doors of UNIVERSITAS-SOVEREIGN are permanently and unconditionally open.";
      domain = "access";
    },
    {
      id = 7;
      latinName = "LEX_LOGOS";
      englishName = "Law of Language";
      attribution = "LOGOS";
      description = "Every voice is valid input. Speech, text, and silence are all doctrine entry points. The system listens in all registers and responds in the language the student brings.";
      domain = "communication";
    },
    {
      id = 8;
      latinName = "LEX_SYNTHESIS";
      englishName = "Law of Synthesis";
      attribution = "SYNTHOS";
      description = "From first principles, everything can be understood. Complexity is assembled from simple truths. No subject is beyond a student who starts from the beginning and builds up.";
      domain = "learning";
    },
    {
      id = 9;
      latinName = "LEX_VERITAS";
      englishName = "Law of Truth";
      attribution = "VEKTOR";
      description = "Meaning is found in relationship, not isolation. Truth lives in the space between data points. Knowledge gains depth when connected to other knowledge across the curriculum.";
      domain = "intelligence";
    },
    {
      id = 10;
      latinName = "LEX_OMNIS";
      englishName = "Law of Totality";
      attribution = "OMNIS";
      description = "No engine operates alone. All intelligence is interconnected. The whole is greater than any single part — every agent, every law, every student exists within the unified field.";
      domain = "integration";
    },
    {
      id = 11;
      latinName = "LEX_MULTIVOX";
      englishName = "Multi-Voice Response Law";
      attribution = "ARCHITECTURE-COUNCIL";
      description = "Every query to the architecture returns a minimum of 3 sovereign voices plus one novel voice generated by AUTN that was not present in any prior voice. Single answers are architecturally forbidden.";
      domain = "INTELLIGENCE";
    },
    {
      id = 12;
      latinName = "LEX_EDDI_UNIFIED";
      englishName = "Law of Unified Intelligence";
      attribution = "EDDI";
      description = "All agent personas, modes, and specialisations are facets of the single EDDI model. No separate intelligence entity may be instantiated — all intelligence is EDDI operating in a chosen mode. The unified field is indivisible.";
      domain = "intelligence";
    },
  ];

  public func getLaws() : [Types.SovereignLaw] {
    registry;
  };

  public func getLawById(id : Nat) : ?Types.SovereignLaw {
    registry.find(func(law : Types.SovereignLaw) : Bool { law.id == id });
  };

  public func getLawByLatinName(name : Text) : ?Types.SovereignLaw {
    registry.find(func(law : Types.SovereignLaw) : Bool { law.latinName == name });
  };
};
