/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccommodationType = { 'other' : string } |
  { 'simplifiedLanguage' : null } |
  { 'reducedDistraction' : null } |
  { 'preferredSeating' : null } |
  { 'breaksBetweenTasks' : null } |
  { 'extendedTime' : null } |
  { 'calculator' : null } |
  { 'spellChecker' : null } |
  { 'readAloud' : null } |
  { 'largeFontSize' : null };
export interface AchievementGapRecord {
  'highGroupAvg' : bigint,
  'computedAt' : bigint,
  'lowGroupAvg' : bigint,
  'districtId' : DistrictId,
  'gapScore' : bigint,
  'subjectId' : bigint,
  'gradeLevel' : bigint,
}
export interface AchievementRecord {
  'id' : string,
  'studentId' : UserId,
  'source' : string,
  'zone' : AchievementZone,
  'sealedAt' : Timestamp,
  'description' : string,
  'achievementType' : AchievementType,
}
export interface AchievementTimelineEntry {
  'eventId' : string,
  'title' : string,
  'domain' : string,
  'year' : bigint,
  'description' : string,
  'grade' : bigint,
  'timestamp' : bigint,
  'programName' : string,
  'goldSealed' : boolean,
  'eventType' : string,
}
export type AchievementType = { 'PaceAnomaly' : null } |
  { 'PerfectScore' : null } |
  { 'MasterySeal' : null } |
  { 'NominationSent' : null } |
  { 'RecognitionFlag' : null };
export type AchievementZone = { 'hot' : null } |
  { 'cold' : null } |
  { 'warm' : null } |
  { 'frozen' : null };
export interface ActivityEntry {
  'action' : string,
  'staffId' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface ActivityRecord {
  'action' : string,
  'studentName' : string,
  'score' : number,
  'timestamp' : bigint,
}
export type AdaptiveAction = { 'remedialReview' : null } |
  { 'continue' : null } |
  { 'quizNow' : null } |
  { 'advance' : null };
export interface AdaptiveSuggestion {
  'action' : SuggestionAction,
  'message' : string,
}
export interface AdaptiveWorkflow {
  'reasonPhrase' : string,
  'fibDifficultyLevel' : bigint,
  'nextAction' : AdaptiveAction,
  'suggestedTopics' : Array<string>,
  'phiConfidence' : number,
}
export interface AdmissionsEvent {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'scheduledDate' : [] | [bigint],
  'notes' : string,
  'eventType' : string,
}
export interface Agent {
  'id' : string,
  'name' : string,
  'role' : AgentRole,
  'protocols' : Array<string>,
  'isActive' : boolean,
  'version' : string,
  'systemPrompt' : string,
  'workspace' : string,
  'registeredAt' : bigint,
  'engine' : string,
}
export type AgentRole = { 'quizmaster' : null } |
  { 'encourager' : null } |
  { 'explainer' : null } |
  { 'guide' : null } |
  { 'curator' : null } |
  { 'assessor' : null };
export interface AllocatorStats {
  'utilizationPct' : number,
  'totalAllocated' : bigint,
  'blockCount' : bigint,
  'zoneDistribution' : Array<bigint>,
  'totalCapacity' : bigint,
}
export interface ApiCallLog {
  'endpointId' : string,
  'callerId' : string,
  'timestamp' : bigint,
  'success' : boolean,
  'responseTime' : bigint,
}
export interface ApiEndpoint {
  'id' : string,
  'method' : string,
  'requiresAuth' : boolean,
  'domain' : string,
  'name' : string,
  'path' : string,
  'sealedAt' : bigint,
  'description' : string,
  'version' : string,
  'substrateDomain' : string,
  'rateLimit' : bigint,
}
export interface ApiStats {
  'activeEndpoints' : bigint,
  'totalCalls' : bigint,
  'totalEndpoints' : bigint,
}
export interface ApiUsageStats {
  'rateLimitTier' : bigint,
  'clientId' : string,
  'totalCalls' : bigint,
  'approvedEndpoints' : Array<string>,
  'lastCall' : bigint,
  'callsThisMinute' : bigint,
}
export interface ApiVersion {
  'endpointCount' : bigint,
  'version' : string,
  'deprecated' : boolean,
  'releaseDate' : bigint,
}
export type ApplicationStatus = { 'expired' : null } |
  { 'applied' : null } |
  { 'awarded' : null } |
  { 'matched' : null } |
  { 'declined' : null } |
  { 'interested' : null };
export interface ArchCouncilVoice {
  'mathBasis' : string,
  'voiceId' : string,
  'answer' : string,
  'confidence' : bigint,
  'engine' : string,
}
export interface AsgnStats {
  'gradedCount' : bigint,
  'avgScore' : bigint,
  'totalAssignments' : bigint,
  'totalSubmissions' : bigint,
}
export interface Assignment {
  'id' : bigint,
  'standardCodes' : Array<string>,
  'title' : string,
  'maxScore' : bigint,
  'createdAt' : bigint,
  'dueDate' : [] | [bigint],
  'description' : string,
  'autoSeedPassport' : boolean,
  'subjectId' : bigint,
  'gradeLevel' : bigint,
  'teacherPrincipal' : Principal,
  'classCode' : string,
}
export interface AttendanceRecord {
  'periodCode' : [] | [string],
  'status' : AttendanceStatus,
  'date' : bigint,
  'sisId' : SisStudentId,
}
export type AttendanceStatus = { 'tardy' : null } |
  { 'present' : null } |
  { 'absent' : null } |
  { 'excused' : null };
export interface BuilderStats {
  'sessionsProcessed' : bigint,
  'workflowCompletions' : bigint,
  'lastActiveAt' : bigint,
  'seedsSealed' : bigint,
}
export interface CalendarEvent {
  'title' : string,
  'schoolId' : bigint,
  'affectedGrades' : Array<bigint>,
  'eventDate' : bigint,
  'eventType' : string,
}
export type CareerCluster = string;
export interface CareerExplorationEntry {
  'exploredAt' : bigint,
  'careerTitle' : string,
  'careerId' : bigint,
  'cluster' : CareerCluster,
  'bookmarked' : boolean,
}
export interface CareerMilestone {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'title' : string,
  'linkedSubjectId' : [] | [bigint],
}
export interface CareerPathway {
  'id' : bigint,
  'recommendedClusters' : Array<CareerCluster>,
  'interestSurveyResults' : Array<InterestScore>,
  'studentPrincipal' : Principal,
  'updatedAt' : bigint,
  'explorationHistory' : Array<CareerExplorationEntry>,
  'milestones' : Array<CareerMilestone>,
}
export interface CatalogCourse {
  'title' : string,
  'gradeMax' : bigint,
  'gradeMin' : bigint,
  'cteProgram' : string,
  'uilProgram' : string,
  'description' : string,
  'phiGateScore' : bigint,
  'totalModules' : bigint,
  'category' : CourseCategory,
  'courseId' : string,
}
export interface CatalogCourseDetail {
  'title' : string,
  'gradeMax' : bigint,
  'gradeMin' : bigint,
  'cteProgram' : string,
  'uilProgram' : string,
  'courseId' : string,
  'modules' : Array<CatalogModule>,
}
export interface CatalogModule {
  'fibMilestone' : bigint,
  'moduleId' : string,
  'title' : string,
  'order' : bigint,
  'description' : string,
}
export interface ClassDetail {
  'students' : Array<StudentSummary>,
  'subject' : string,
  'classId' : string,
  'recentActivity' : Array<ActivityRecord>,
  'grade' : bigint,
  'className' : string,
}
export interface ClassHeatmap {
  'needsSupport' : Array<string>,
  'highPerformers' : Array<string>,
  'subject' : string,
  'topicMastery' : Array<[string, bigint]>,
  'classId' : string,
  'gradeLevel' : bigint,
  'timestamp' : bigint,
  'avgClassMastery' : bigint,
}
export interface ClassHeatmapData {
  'subject' : string,
  'activeStudents' : bigint,
  'classId' : string,
  'grade' : bigint,
  'sessionCount' : bigint,
  'lastActive' : bigint,
  'avgMastery' : bigint,
}
export interface ClassRecord {
  'subject' : string,
  'classId' : string,
  'grade' : bigint,
  'className' : string,
  'studentCount' : bigint,
  'avgMastery' : number,
}
export interface ClassRoster {
  'subjectId' : bigint,
  'gradeLevel' : bigint,
  'teacherPrincipal' : Principal,
  'studentSisIds' : Array<SisStudentId>,
  'classCode' : string,
}
export interface ClassSessionMetrics {
  'rcgnStream' : bigint,
  'classId' : string,
  'sssAvg' : bigint,
  'activeCount' : bigint,
  'masteryAvg' : bigint,
  'className' : string,
}
export interface ClrdStats {
  'collegeListSize' : bigint,
  'totalRecords' : bigint,
  'avgApCourseCount' : bigint,
}
export type ClubCategory = { 'other' : string } |
  { 'arts' : null } |
  { 'civic' : null } |
  { 'stem' : null } |
  { 'community' : null } |
  { 'academic' : null } |
  { 'sports' : null };
export interface ClubMembership {
  'clubId' : bigint,
  'joinedAt' : bigint,
  'role' : ClubRole,
  'studentPrincipal' : Principal,
  'linkedAchvId' : [] | [bigint],
  'hoursLogged' : bigint,
}
export interface ClubRecord {
  'id' : bigint,
  'active' : boolean,
  'memberPrincipals' : Array<Principal>,
  'name' : string,
  'createdAt' : bigint,
  'schoolId' : bigint,
  'category' : ClubCategory,
  'advisorPrincipal' : Principal,
}
export type ClubRole = { 'member' : null } |
  { 'vicePresident' : null } |
  { 'secretary' : null } |
  { 'treasurer' : null } |
  { 'officer' : null } |
  { 'president' : null };
export interface CollegeEntry {
  'matchTier' : CollegeMatchTier,
  'collegeName' : string,
  'applicationStatus' : string,
  'addedAt' : bigint,
}
export type CollegeMatchTier = { 'safety' : null } |
  { 'target' : null } |
  { 'reach' : null };
export interface CollegeReadinessRecord {
  'apCourseIds' : Array<bigint>,
  'studentPrincipal' : Principal,
  'transcriptMilestones' : Array<TranscriptMilestone>,
  'updatedAt' : bigint,
  'ibCourseIds' : Array<bigint>,
  'collegeExplorationList' : Array<CollegeEntry>,
  'admissionsTimeline' : Array<AdmissionsEvent>,
}
export type CollegeReadinessStage = { 'preparing' : null } |
  { 'applying' : null } |
  { 'committed' : null } |
  { 'exploring' : null } |
  { 'planning' : null };
export interface CommMessage {
  'id' : bigint,
  'expiresAt' : [] | [bigint],
  'subject' : string,
  'body' : string,
  'sender' : Principal,
  'sentAt' : bigint,
  'messageType' : MessageType,
  'recipientRefs' : Array<RecipientRef>,
  'attachmentHashes' : Array<Uint8Array>,
  'translationNeeded' : boolean,
}
export interface CommStats {
  'byType' : Array<[string, bigint]>,
  'translationRequestCount' : bigint,
  'totalMessages' : bigint,
  'unreadCount' : bigint,
}
export interface CompetitionTemplate {
  'name' : string,
  'description' : string,
  'prepWeeksTypical' : bigint,
  'domains' : Array<string>,
  'category' : CourseCategory,
  'organization' : string,
}
export interface ContactPreferences {
  'preferEmail' : boolean,
  'preferInApp' : boolean,
  'language' : string,
  'quietHoursStart' : [] | [bigint],
  'quietHoursEnd' : [] | [bigint],
}
export interface CounPlanStats {
  'withCareerPathway' : bigint,
  'milestoneCompletionRate' : bigint,
  'iepFlaggedCount' : bigint,
  'totalPlans' : bigint,
}
export interface CounselorMilestone {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'title' : string,
  'targetDate' : [] | [bigint],
  'category' : MilestoneCategory,
}
export interface CounselorPlan {
  'collegeReadinessStage' : [] | [CollegeReadinessStage],
  'accommodationTypes' : Array<string>,
  'createdAt' : bigint,
  'studentPrincipal' : Principal,
  'updatedAt' : bigint,
  'notes' : string,
  'careerPathwayId' : [] | [bigint],
  'iepFlagged' : boolean,
  'counselorPrincipal' : Principal,
  'milestones' : Array<CounselorMilestone>,
}
export interface Course {
  'id' : string,
  'title' : string,
  'requiredSssThreshold' : bigint,
  'order' : bigint,
  'description' : string,
  'moduleCount' : bigint,
  'category' : string,
}
export type CourseCategory = { 'FFA' : null } |
  { 'CTE_HEALTH' : null } |
  { 'CTE_HVAC' : null } |
  { 'UIL_MATH' : null } |
  { 'DECA' : null } |
  { 'HOSA' : null } |
  { 'CTE_CONSTRUCTION' : null } |
  { 'ACADEMICS' : null } |
  { 'CTE_COSMETOLOGY' : null } |
  { 'SKILLS_USA' : null } |
  { 'UIL_MUSIC' : null } |
  { 'CTE_AUTOMOTIVE' : null } |
  { 'CTE_WELDING' : null } |
  { 'UIL_SPEECH' : null } |
  { 'CTE_ROBOTICS' : null } |
  { 'UIL_ENGLISH' : null } |
  { 'UIL_SCIENCE' : null } |
  { 'CTE_CULINARY' : null };
export interface CourseSummary {
  'progressPercent' : bigint,
  'isEnrolled' : boolean,
  'course' : Course,
  'isUnlocked' : boolean,
}
export interface CrossSchoolTrend {
  'schoolId' : SchoolId,
  'subjectId' : bigint,
  'gradeLevel' : bigint,
  'periodLabel' : string,
  'sessionCount' : bigint,
  'avgMastery' : bigint,
}
export interface CrptStats {
  'avgExplorationDepth' : bigint,
  'totalPathways' : bigint,
  'topClusters' : Array<[CareerCluster, bigint]>,
}
export interface DigestJob {
  'status' : string,
  'completedAt' : bigint,
  'title' : string,
  'quizSeeds' : bigint,
  'subject' : string,
  'jobId' : string,
  'submittedAt' : bigint,
  'gradeLevel' : bigint,
  'teacherId' : string,
  'conceptsFound' : bigint,
}
export interface DigestResult {
  'status' : string,
  'quizSeedsGenerated' : bigint,
  'jobId' : string,
  'gradeVaultEntryId' : string,
  'conceptsExtracted' : Array<DigtConcept>,
  'workedExamplesGenerated' : bigint,
}
export interface DigestStatus {
  'status' : string,
  'completedAt' : bigint,
  'jobId' : string,
  'progress' : bigint,
}
export interface DigtConcept {
  'id' : string,
  'subject' : string,
  'difficulty' : bigint,
  'term' : string,
  'gradeLevel' : bigint,
  'fibWeight' : bigint,
  'definition' : string,
}
export interface DigtDigestResult {
  'subject' : string,
  'quizSeedsGenerated' : bigint,
  'workedExamplesFound' : bigint,
  'conceptsExtracted' : bigint,
  'gradeLevel' : bigint,
  'processingCycles' : bigint,
  'timestamp' : bigint,
  'inputId' : string,
}
export interface DigtQuizSeed {
  'id' : string,
  'question' : string,
  'subject' : string,
  'conceptId' : string,
  'answer' : string,
  'distractors' : Array<string>,
  'gradeLevel' : bigint,
}
export interface DigtStats {
  'totalInputs' : bigint,
  'subjectsDigested' : Array<string>,
  'totalConcepts' : bigint,
  'totalQuizSeeds' : bigint,
}
export interface DigtStatus {
  'lastDigested' : [] | [bigint],
  'conceptCount' : bigint,
  'quizSeedCount' : bigint,
  'standardId' : string,
  'hasContent' : boolean,
}
export type DistrictId = bigint;
export interface DistrictProfile {
  'id' : DistrictId,
  'name' : string,
  'createdAt' : bigint,
  'schoolIds' : Array<SchoolId>,
  'state' : string,
  'contactEmail' : string,
}
export interface DistrictStats {
  'totalSchools' : bigint,
  'avgMasteryScore' : bigint,
  'totalStudents' : bigint,
  'achievementGapIndex' : bigint,
}
export interface EDDI {
  'id' : string,
  'law' : string,
  'modeCount' : bigint,
  'name' : string,
  'sealedAt' : Timestamp,
  'version' : bigint,
}
export type EDDIMode = { 'STUDENT_MODE' : null } |
  { 'ARCHITECT_MODE' : null } |
  { 'RECOGNITION_MODE' : null } |
  { 'TEACHER_MODE' : null } |
  { 'BUILD_MODE' : null } |
  { 'PRINCIPAL_MODE' : null } |
  { 'MEMORY_MODE' : null };
export interface EchoResult {
  'coherenceDelta' : bigint,
  'newCoherence' : bigint,
  'passportUpdated' : boolean,
}
export interface EligibleProgram {
  'url' : string,
  'name' : string,
  'description' : string,
}
export type EngineStatus = { 'active' : null } |
  { 'dormant' : null };
export type EnrichmentType = { 'STEMEvent' : null } |
  { 'other' : string } |
  { 'museumVisit' : null } |
  { 'guestSpeaker' : null } |
  { 'labVisit' : null } |
  { 'fieldTrip' : null };
export interface EnrolledCourse {
  'completedModules' : Array<bigint>,
  'agentsBuilt' : Array<string>,
  'progressPercent' : bigint,
  'enrolledAt' : Timestamp,
  'courseId' : string,
}
export interface EnrollmentResult {
  'firstModuleContent' : string,
  'eddiBrief' : string,
  'firstModuleTitle' : string,
  'passportSeeded' : boolean,
  'success' : boolean,
  'firstModuleId' : string,
}
export type EnrollmentStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'transferred' : null } |
  { 'graduated' : null };
export type EntanglementDirection = { 'bidirectional' : null } |
  { 'unidirectional' : null };
export interface EntanglementRecord {
  'id' : string,
  'status' : EntanglementStatus,
  'direction' : EntanglementDirection,
  'targetSubstrate' : string,
  'name' : string,
  'coherenceDelta' : bigint,
  'lastEntanglement' : bigint,
  'transitCount' : bigint,
  'sourceSubstrate' : string,
}
export type EntanglementStatus = { 'active' : null } |
  { 'dormant' : null };
export interface EslProfile {
  'preferredLanguage' : string,
  'studentPrincipal' : Principal,
  'updatedAt' : bigint,
  'proficiencyLevel' : ProficiencyLevel,
  'translationFlags' : Array<string>,
  'vocabScaffoldingEnabled' : boolean,
  'adaptedPromptsEnabled' : boolean,
  'nativeLanguage' : string,
}
export interface EsllStats {
  'totalEllStudents' : bigint,
  'scaffoldingEnabledCount' : bigint,
  'byProficiencyLevel' : Array<[string, bigint]>,
}
export interface FeedbackEvent {
  'id' : string,
  'resolved' : boolean,
  'userId' : UserId,
  'createdAt' : bigint,
  'eddiResponse' : string,
  'message' : string,
  'severity' : string,
  'selfCorrectionAttempts' : bigint,
  'itEscalated' : boolean,
  'proposedFix' : [] | [string],
  'resolvedAt' : [] | [bigint],
}
export interface FieldTripRecord {
  'id' : bigint,
  'passportArchived' : boolean,
  'activityDate' : bigint,
  'organizer' : Principal,
  'title' : string,
  'attendeeCount' : bigint,
  'postAssessmentId' : [] | [bigint],
  'schoolId' : bigint,
  'gradeLevel' : bigint,
  'attendeePrincipals' : Array<Principal>,
  'enrichmentType' : EnrichmentType,
  'location' : string,
  'preAssessmentId' : [] | [bigint],
}
export interface FluxState {
  'difficultyLevel' : bigint,
  'phiRatio' : bigint,
  'masteryFloor' : bigint,
  'phiConfidence' : bigint,
  'nextFloorThreshold' : bigint,
}
export interface FtrpStats {
  'byType' : Array<[string, bigint]>,
  'totalActivities' : bigint,
  'passportArchivedCount' : bigint,
  'totalAttendees' : bigint,
}
export interface FundingEntry {
  'entryId' : string,
  'stage' : FundingStage,
  'targetAmount' : bigint,
  'notes' : string,
  'timestamp' : bigint,
  'contactEmail' : string,
  'programName' : string,
}
export interface FundingEntryInput {
  'stage' : string,
  'targetAmount' : bigint,
  'notes' : string,
  'contactEmail' : string,
  'programName' : string,
}
export interface FundingEntryResult { 'entryId' : string, 'success' : boolean }
export type FundingStage = { 'DECLINED' : null } |
  { 'PENDING' : null } |
  { 'IDENTIFIED' : null } |
  { 'APPLIED' : null } |
  { 'AWARDED' : null };
export interface FundingTarget {
  'status' : string,
  'name' : string,
  'amount' : string,
}
export interface GradeCount {
  'grade' : bigint,
  'activeSessionCount' : bigint,
  'studentCount' : bigint,
  'avgMastery' : number,
}
export interface GradeDrilldown {
  'fibCycleStamp' : bigint,
  'masteryDistribution' : Array<[string, bigint]>,
  'totalStudents' : bigint,
  'grade' : bigint,
  'subjectBreakdown' : Array<[string, bigint]>,
  'strugglingStudents' : Array<string>,
}
export interface GradeGate {
  'studentGrade' : bigint,
  'requestedGrade' : bigint,
  'allowed' : boolean,
  'reason' : string,
}
export type GradeLevel = string;
export interface GradePerformance {
  'subject' : string,
  'lastUpdated' : bigint,
  'topicBreakdown' : Array<[string, bigint]>,
  'studentsAtLevel' : bigint,
  'weeklyTrend' : Array<bigint>,
  'gradeLevel' : bigint,
  'avgMastery' : bigint,
}
export interface GradeRecord {
  'maxScore' : bigint,
  'gradedAt' : bigint,
  'gradedBy' : Principal,
  'studentPrincipal' : Principal,
  'feedback' : string,
  'score' : bigint,
  'passportSeedId' : [] | [bigint],
  'assignmentId' : bigint,
  'submissionId' : bigint,
}
export interface GradeVaultEntry {
  'contentId' : string,
  'subject' : string,
  'contentType' : string,
  'lockedUntilGrade' : bigint,
  'gradeLevel' : bigint,
}
export interface GradeVaultSummary {
  'weeklyProgress' : Array<WeekProgress>,
  'totalStudents' : bigint,
  'topSubject' : string,
  'grade' : bigint,
  'strugglingSubject' : string,
  'avgMastery' : number,
}
export interface GroupSession {
  'id' : bigint,
  'startedAt' : bigint,
  'groupId' : bigint,
  'durationMinutes' : bigint,
  'participantCount' : bigint,
  'sharedMasteryDelta' : bigint,
}
export interface GrowthMilestone {
  'title' : string,
  'achievedAt' : bigint,
  'category' : string,
}
export interface GvltStats {
  'totalAllowed' : bigint,
  'totalEntries' : bigint,
  'totalBlocked' : bigint,
}
export interface HeatmapWithNoms {
  'subject' : string,
  'recentAchievements' : bigint,
  'activeStudents' : bigint,
  'classId' : string,
  'grade' : bigint,
  'pendingNoms' : bigint,
  'sessionCount' : bigint,
  'lastActive' : bigint,
  'avgMastery' : bigint,
}
export interface IasResult { 'layoutState' : string, 'iasScore' : bigint }
export interface IepAccommodation {
  'active' : boolean,
  'accommodationTypes' : Array<AccommodationType>,
  'reviewDate' : [] | [bigint],
  'studentPrincipal' : Principal,
  'addedBy' : Principal,
  'effectiveFrom' : bigint,
}
export interface IesmStats {
  'activeAccomCount' : bigint,
  'totalStudentsWithAccom' : bigint,
  'mostCommonAccom' : string,
}
export interface ImpactResult {
  'projectedNominationsPerYear' : bigint,
  'totalStudents' : bigint,
  'estimatedRecognitionsPerYear' : bigint,
  'costPerStudent' : number,
  'roiForDistrict' : string,
}
export interface IncidentEntry {
  'description' : string,
  'timestamp' : bigint,
  'severity' : IncidentSeverity,
}
export type IncidentSeverity = { 'major' : null } |
  { 'minor' : null } |
  { 'moderate' : null };
export interface InterestScore {
  'score' : bigint,
  'surveyDate' : bigint,
  'cluster' : CareerCluster,
}
export interface KernelSeed {
  'id' : string,
  'artifactName' : [] | [string],
  'trackName' : string,
  'createdAt' : Timestamp,
  'sessionSummary' : string,
  'engineUsed' : string,
}
export interface KnowledgeQuery {
  'subject' : string,
  'studentGrade' : GradeLevel,
  'includeGradeRange' : boolean,
}
export interface KnowledgeResult {
  'subject' : string,
  'lockedForStudent' : boolean,
  'topics' : Array<Topic>,
  'gradeLevel' : GradeLevel,
}
export interface LbryStats {
  'overdueCount' : bigint,
  'masteryLinkedCount' : bigint,
  'totalCheckouts' : bigint,
  'activeCheckouts' : bigint,
}
export interface LibraryRecord {
  'id' : bigint,
  'title' : string,
  'masteryLinked' : boolean,
  'resourceId' : string,
  'checkedOutAt' : bigint,
  'linkedSubjectId' : [] | [bigint],
  'studentPrincipal' : Principal,
  'dueDate' : [] | [bigint],
  'resourceType' : ResourceType,
  'readingProgressPct' : bigint,
  'returnedAt' : [] | [bigint],
}
export interface LiveIntelligenceState {
  'adx' : bigint,
  'coh' : bigint,
  'ias' : bigint,
  'sss' : bigint,
  'isGoldMoment' : boolean,
  'layoutState' : string,
  'rcgnThreshold' : bigint,
}
export interface LiveMetrics {
  'totalQueriesThisHour' : bigint,
  'fibonacciCycleCount' : bigint,
  'avgCoherenceScore' : bigint,
  'activeStudents' : bigint,
  'topSubject' : string,
  'timestamp' : bigint,
  'activeSessions' : bigint,
}
export interface LiveSessionMetrics {
  'topSubjects' : Array<string>,
  'totalActiveSessions' : bigint,
  'timestamp' : bigint,
  'studentsOnline' : bigint,
  'systemCoherence' : bigint,
}
export interface MLTVResponse {
  'voices' : Array<ArchCouncilVoice>,
  'totalCoherence' : bigint,
  'queryId' : string,
  'timestamp' : bigint,
  'fibFlooredAt' : bigint,
  'novelVoice' : ArchCouncilVoice,
}
export interface MLTVStats {
  'totalVoices' : bigint,
  'totalQueries' : bigint,
  'avgCoherence' : bigint,
  'novelAnswersGenerated' : bigint,
}
export interface MentalHealthCheckIn {
  'recordedAt' : bigint,
  'anonymousNote' : [] | [string],
  'schoolId' : bigint,
  'gradeLevel' : bigint,
  'sessionToken' : Uint8Array,
  'moodScore' : bigint,
}
export interface MessageRef {
  'messageId' : bigint,
  'subject' : string,
  'read' : boolean,
  'sentAt' : bigint,
}
export type MessageType = { 'parentTeacherMessage' : null } |
  { 'systemNotice' : null } |
  { 'eventInvitation' : null } |
  { 'alert' : null } |
  { 'announcement' : null } |
  { 'recognitionAlert' : null } |
  { 'progressUpdate' : null };
export type MilestoneCategory = { 'social' : null } |
  { 'academic' : null } |
  { 'postsecondary' : null } |
  { 'career' : null } |
  { 'college' : null };
export interface MoodAggregate {
  'lowMoodCount' : bigint,
  'highMoodCount' : bigint,
  'periodEnd' : bigint,
  'schoolId' : bigint,
  'periodStart' : bigint,
  'checkInCount' : bigint,
  'avgMoodScore' : bigint,
}
export interface MsryState {
  'fibonacciFloorLevel' : bigint,
  'zone' : string,
  'lastZoneTransition' : bigint,
  'seedCount' : bigint,
  'masteryCompound' : bigint,
}
export interface NexumGateEntry {
  'studentId' : Principal,
  'appliedLaw' : string,
  'collegium' : string,
  'enteredAt' : bigint,
}
export interface NominationRecord {
  'id' : string,
  'status' : NominationStatus,
  'studentId' : UserId,
  'submittedAt' : Timestamp,
  'teacherNote' : string,
  'programName' : string,
}
export type NominationStatus = { 'submitted' : null } |
  { 'confirmed' : null } |
  { 'draft' : null };
export interface NrveState {
  'coherenceScore' : bigint,
  'activeEngine' : string,
  'phiRatio' : bigint,
  'cogtPhase' : string,
  'cycleCount' : bigint,
}
export type ParentId = Principal;
export interface ParentRecord {
  'contactPrefs' : ContactPreferences,
  'linkedStudentPrincipals' : Array<Principal>,
  'displayName' : string,
  'createdAt' : bigint,
  'messageHistory' : Array<MessageRef>,
  'permissionLevel' : PermissionLevel,
  'parentId' : ParentId,
}
export interface PassportInsight {
  'eddiBrief' : string,
  'frozenSeeds' : bigint,
  'orbMode' : string,
  'sssScore' : bigint,
  'seedCount' : bigint,
  'hotSeeds' : bigint,
  'warmSeeds' : bigint,
  'coldSeeds' : bigint,
}
export interface PassportStats {
  'frozenSeeds' : bigint,
  'totalSeeds' : bigint,
  'achievements' : Array<string>,
  'hotSeeds' : bigint,
  'warmSeeds' : bigint,
  'coldSeeds' : bigint,
  'compoundScore' : number,
}
export interface PdRecord {
  'id' : bigint,
  'completedAt' : bigint,
  'title' : string,
  'provider' : string,
  'growthMilestone' : [] | [GrowthMilestone],
  'certificationEarned' : [] | [string],
  'pdType' : PdType,
  'teacherPrincipal' : Principal,
  'hoursLogged' : bigint,
}
export type PdType = { 'workshop' : null } |
  { 'other' : string } |
  { 'conference' : null } |
  { 'peerCoaching' : null } |
  { 'onlineCourse' : null } |
  { 'certification' : null } |
  { 'selfStudy' : null };
export type PermissionLevel = { 'full' : null } |
  { 'readOnly' : null } |
  { 'standard' : null };
export interface PgrpStats {
  'avgGroupSize' : bigint,
  'avgMasteryGain' : bigint,
  'totalSessions' : bigint,
  'totalGroups' : bigint,
}
export interface PlseNudge { 'ttl' : bigint, 'prompt' : string }
export interface PlseSeed { 'concept' : string, 'timestamp' : bigint }
export interface PlseState {
  'phiHeartbeatInterval' : bigint,
  'curiosityQueue' : Array<PlseNudge>,
  'heartbeatCycle' : bigint,
  'lastAutonSeed' : PlseSeed,
}
export interface PortalTransition {
  'toPortal' : string,
  'fromPortal' : string,
  'userId' : string,
  'timestamp' : bigint,
}
export interface PrcpNarrativeEntry {
  'studentsAccelerating' : bigint,
  'classId' : string,
  'studentsAtRisk' : bigint,
  'narrative' : string,
  'masteryAvg' : bigint,
  'sessionCount' : bigint,
  'className' : string,
  'rcgnEvents' : bigint,
}
export type ProficiencyLevel = { 'bridging' : null } |
  { 'entering' : null } |
  { 'developing' : null } |
  { 'emerging' : null } |
  { 'expanding' : null } |
  { 'reaching' : null };
export interface QueryResult {
  'totalFound' : bigint,
  'target' : string,
  'queryId' : string,
  'timestamp' : bigint,
  'items' : Array<QueryResultItem>,
  'fibFlooredAt' : bigint,
  'executionCycles' : bigint,
}
export interface QueryResultItem {
  'id' : string,
  'data' : string,
  'score' : bigint,
}
export interface QuizResult {
  'agentId' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
  'quizType' : QuizType,
  'topicId' : string,
}
export type QuizType = { 'freeResponse' : null } |
  { 'multipleChoice' : null };
export interface RcgnAlert {
  'alertType' : string,
  'studentId' : string,
  'studentName' : string,
  'subject' : string,
  'threshold' : bigint,
  'timestamp' : bigint,
  'rcgnScore' : bigint,
  'nominationReady' : boolean,
}
export type RecipientRef = { 'schoolWide' : bigint } |
  { 'teacher' : Principal } |
  { 'gradeLevel' : bigint } |
  { 'student' : Principal } |
  { 'classCode' : string } |
  { 'parent' : Principal };
export interface RecognitionFlag {
  'id' : string,
  'pattern' : RecognitionPattern,
  'studentId' : UserId,
  'subject' : string,
  'detectedAt' : Timestamp,
  'masteryScore' : bigint,
  'eligiblePrograms' : Array<EligibleProgram>,
  'sealed' : boolean,
}
export type RecognitionPattern = { 'PaceAnomaly' : null } |
  { 'PerfectScore' : null } |
  { 'SubjectExcellence' : null } |
  { 'SustainedMastery' : null };
export interface RecognitionTimelineEntry {
  'id' : string,
  'isGoldMoment' : boolean,
  'source' : string,
  'zone' : string,
  'sealedAt' : bigint,
  'description' : string,
  'achievementType' : string,
  'gradeContext' : string,
}
export interface RegistrationRequest {
  'status' : string,
  'requestId' : string,
  'name' : string,
  'submittedAt' : bigint,
  'description' : string,
  'requestedEndpoints' : Array<string>,
}
export interface RegistrationResult {
  'status' : string,
  'clientId' : string,
  'apiKey' : string,
  'rateLimitPerMinute' : bigint,
  'approvedEndpoints' : Array<string>,
}
export type ResourceType = { 'referenceDoc' : null } |
  { 'periodical' : null } |
  { 'other' : string } |
  { 'video' : null } |
  { 'book' : null } |
  { 'ebook' : null } |
  { 'audiobook' : null };
export interface SchfStats {
  'totalMatches' : bigint,
  'awardedCount' : bigint,
  'topCategories' : Array<[string, bigint]>,
  'totalPrograms' : bigint,
}
export interface ScholarshipMatch {
  'id' : bigint,
  'matchedAt' : bigint,
  'studentPrincipal' : Principal,
  'matchScore' : bigint,
  'applicationStatus' : ApplicationStatus,
  'notes' : string,
  'programId' : bigint,
}
export interface ScholarshipProgram {
  'id' : bigint,
  'url' : string,
  'categories' : Array<string>,
  'name' : string,
  'deadline' : [] | [bigint],
  'sponsor' : string,
  'eligibilityCriteria' : Array<string>,
  'awardAmount' : [] | [bigint],
}
export type SchoolId = bigint;
export interface ScoreProjection {
  'computedAt' : bigint,
  'mode' : TestPrepMode,
  'studentPrincipal' : Principal,
  'sessionsUsed' : bigint,
  'confidenceLevel' : bigint,
  'projectedScore' : bigint,
}
export interface SdkEntry {
  'id' : string,
  'status' : string,
  'name' : string,
  'entryPoints' : Array<string>,
  'description' : string,
  'version' : string,
  'category' : string,
  'accessProtocol' : string,
}
export interface SelfStudyMilestone {
  'completedAt' : [] | [bigint],
  'title' : string,
  'domain' : string,
  'masteryScore' : bigint,
  'description' : string,
  'weeksBefore' : bigint,
  'isComplete' : boolean,
}
export interface SelfStudyTrack {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'passportSealed' : boolean,
  'masteryPct' : bigint,
  'category' : string,
  'competitionDate' : bigint,
  'milestones' : Array<SelfStudyMilestone>,
}
export interface SessionMetrics {
  'activeStudents' : bigint,
  'activeSessions' : bigint,
  'classBreakdown' : Array<ClassSessionMetrics>,
}
export type SessionMode = { 'freeAfternoon' : null } |
  { 'workNight' : null };
export interface SessionSchedule {
  'compressRatio' : number,
  'mode' : SessionMode,
  'nextReviewAt' : bigint,
  'missedCount' : bigint,
  'intervalMinutes' : bigint,
}
export interface SilverBuilder {
  'id' : string,
  'protocol' : string,
  'status' : SilverBuilderStatus,
  'domain' : string,
  'createdAt' : bigint,
  'domainsOwned' : Array<string>,
  'codeName' : string,
  'purpose' : string,
}
export type SilverBuilderStatus = { 'active' : null } |
  { 'sealed' : null } |
  { 'dormant' : null };
export interface SisRecord {
  'studentPrincipal' : [] | [Principal],
  'enrollmentStatus' : EnrollmentStatus,
  'sisId' : SisStudentId,
  'updatedAt' : bigint,
  'schoolId' : bigint,
  'grade' : bigint,
}
export type SisStudentId = string;
export interface SkaiDocensInfo {
  'protocol' : string,
  'doctrine' : string,
  'title' : string,
  'name' : string,
}
export interface SkaiTeachResponse {
  'doctrine' : string,
  'engineSelected' : string,
  'suggestedNext' : string,
  'studentWelcome' : string,
}
export interface SonrStatus {
  'coh' : number,
  'pil' : number,
  'status' : { 'quiet' : null } |
    { 'mutaTriggered' : null },
  'risk' : number,
}
export interface SovereignEngine {
  'id' : bigint,
  'status' : EngineStatus,
  'domain' : string,
  'fullName' : string,
  'description' : string,
  'codeName' : string,
  'mathFoundation' : string,
  'teachingMethod' : string,
  'lessonsAvailable' : Array<string>,
  'platformRole' : string,
}
export interface SovereignLaw {
  'id' : bigint,
  'latinName' : string,
  'domain' : string,
  'description' : string,
  'englishName' : string,
  'attribution' : string,
}
export interface SovereignPassport {
  'studentName' : string,
  'lastActiveAt' : Timestamp,
  'createdAt' : Timestamp,
  'passportId' : string,
  'collegium' : string,
  'achievements' : Array<string>,
  'gradeLevel' : string,
  'holder' : UserId,
  'totalSessions' : bigint,
  'kernelSeeds' : Array<KernelSeed>,
}
export interface StaffMember {
  'accessLevel' : bigint,
  'staffId' : string,
  'name' : string,
  'role' : StaffRole,
  'department' : string,
  'lastActive' : bigint,
}
export type StaffRole = { 'STAFF_ADMIN' : null } |
  { 'STAFF_SUPPORT' : null } |
  { 'STAFF_COACH' : null } |
  { 'STAFF_COUNSELOR' : null } |
  { 'STAFF_LIBRARIAN' : null } |
  { 'STAFF_IT' : null };
export interface Standard {
  'strand' : [] | [string],
  'subject' : string,
  'code' : StandardCode,
  'framework' : StandardFramework,
  'description' : string,
  'bloomsLevel' : [] | [bigint],
  'gradeLevel' : bigint,
  'fibWeight' : bigint,
}
export interface StandardAlignment {
  'contentId' : bigint,
  'masteryThreshold' : bigint,
  'standardCode' : StandardCode,
  'alignedAt' : bigint,
}
export type StandardCode = string;
export type StandardFramework = { 'NGSS' : null } |
  { 'TEKS' : null } |
  { 'WIDA' : null } |
  { 'CommonCore' : null } |
  { 'Other' : string };
export interface StandardWithDigestStatus {
  'lastDigested' : [] | [bigint],
  'conceptCount' : bigint,
  'quizSeedCount' : bigint,
  'hasContent' : boolean,
  'standard' : Standard,
}
export interface StndStats {
  'totalStandards' : bigint,
  'byFramework' : Array<[string, bigint]>,
  'byGrade' : Array<[bigint, bigint]>,
}
export interface StudentMasteryCard {
  'subjectMastery' : Array<[string, bigint]>,
  'studentId' : string,
  'predictedStruggle' : Array<string>,
  'name' : string,
  'gradeLevel' : bigint,
  'recommendation' : string,
  'lastActive' : bigint,
  'currentStreak' : bigint,
}
export interface StudentProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'gradeLevel' : GradeLevel,
}
export interface StudentSummary {
  'studentId' : string,
  'name' : string,
  'masteryScore' : number,
  'currentTopic' : string,
  'lastActive' : bigint,
}
export interface StudyGroup {
  'id' : bigint,
  'active' : boolean,
  'memberPrincipals' : Array<Principal>,
  'createdAt' : bigint,
  'sssRangeHigh' : bigint,
  'subjectId' : bigint,
  'gradeLevel' : bigint,
  'sssRangeLow' : bigint,
}
export type SubAccessLevel = { 'readOnly' : null } |
  { 'limited' : null };
export interface SubRecord {
  'id' : bigint,
  'accessLevel' : SubAccessLevel,
  'date' : bigint,
  'coveringTeacherPrincipal' : Principal,
  'subPrincipal' : Principal,
  'incidentLog' : Array<IncidentEntry>,
  'classCode' : string,
  'handoffNotes' : string,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'gradeLevel' : string,
}
export interface SubjectTemplate {
  'subject' : string,
  'templateId' : string,
  'createdBy' : string,
  'masterLocked' : boolean,
  'topicIds' : Array<string>,
  'gradeLevel' : GradeLevel,
  'standardsRef' : Array<string>,
}
export interface Submission {
  'id' : bigint,
  'status' : SubmissionStatus,
  'contentHash' : Uint8Array,
  'studentPrincipal' : Principal,
  'submittedAt' : bigint,
  'assignmentId' : bigint,
}
export type SubmissionStatus = { 'graded' : null } |
  { 'submitted' : null } |
  { 'pending' : null } |
  { 'returned' : null };
export interface SubsStats {
  'avgDailySubCount' : bigint,
  'totalSubRecords' : bigint,
  'totalIncidents' : bigint,
}
export type SuggestionAction = { 'remedialReview' : null } |
  { 'continue' : null } |
  { 'quizNow' : null } |
  { 'advance' : null };
export interface SystemMetrics {
  'avgPlatformMastery' : number,
  'totalLessonsCompleted' : bigint,
  'totalStudents' : bigint,
  'activeSessions' : bigint,
}
export interface TchrStats {
  'recommendationsGenerated' : bigint,
  'totalClasses' : bigint,
  'totalStudents' : bigint,
}
export interface TeacherClass {
  'id' : string,
  'subject' : string,
  'name' : string,
  'createdAt' : bigint,
  'studentIds' : Array<string>,
  'gradeLevel' : bigint,
  'teacherId' : string,
}
export interface TeacherClassMetrics {
  'lastActivity' : bigint,
  'currentTopic' : string,
  'advancedCount' : bigint,
  'classId' : string,
  'strugglingCount' : bigint,
  'className' : string,
  'studentCount' : bigint,
  'avgMastery' : bigint,
}
export interface TeacherRecommendation {
  'affectedStudents' : Array<string>,
  'action' : string,
  'novelApproach' : string,
  'suggestedEngine' : string,
  'classId' : string,
  'priority' : bigint,
}
export type TestPrepMode = { 'AP' : string } |
  { 'ACT' : null } |
  { 'SAT' : null } |
  { 'STAAR' : null } |
  { 'PSAT' : null };
export interface TestPrepSession {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'startedAt' : bigint,
  'mode' : TestPrepMode,
  'questionsAttempted' : bigint,
  'studentPrincipal' : Principal,
  'subjectId' : bigint,
  'masteryDelta' : bigint,
  'correctCount' : bigint,
  'strategyNotes' : Array<string>,
}
export type Timestamp = bigint;
export interface Topic {
  'id' : string,
  'title' : string,
  'description' : string,
  'subjectId' : string,
  'gradeLevel' : string,
}
export interface TpdfStats {
  'totalCertificationsEarned' : bigint,
  'totalTeachers' : bigint,
  'avgHoursPerTeacher' : bigint,
  'totalHoursLogged' : bigint,
}
export interface TprpStats {
  'byMode' : Array<[string, bigint]>,
  'avgMasteryDelta' : bigint,
  'totalSessions' : bigint,
}
export interface Track {
  'id' : TrackId,
  'title' : string,
  'description' : string,
  'codeName' : string,
  'durationMinutes' : bigint,
  'stepCount' : bigint,
  'guidingEngines' : Array<string>,
  'subtitle' : string,
}
export interface TrackEnrollment {
  'completedAt' : [] | [bigint],
  'studentId' : Principal,
  'currentStep' : bigint,
  'trackId' : TrackId,
  'enrolledAt' : bigint,
  'createdArtifactName' : [] | [string],
}
export type TrackId = { 'giveAIAVoice' : null } |
  { 'buildFirstAI' : null } |
  { 'teachAIToRemember' : null };
export interface TranscriptMilestone {
  'id' : bigint,
  'completedAt' : [] | [bigint],
  'title' : string,
  'gradeLevel' : bigint,
  'gpaImpact' : [] | [bigint],
}
export type TutorType = { 'peer' : null } |
  { 'teacher' : null };
export interface TutoringSession {
  'id' : bigint,
  'startedAt' : bigint,
  'studentPrincipal' : Principal,
  'sealed' : boolean,
  'tutorRef' : string,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
  'gradeLevel' : bigint,
  'transcriptHash' : [] | [Uint8Array],
  'tutorType' : TutorType,
  'masteryDeltaAfter' : bigint,
  'masteryDeltaBefore' : bigint,
}
export interface UserAgent {
  'id' : string,
  'owner' : UserId,
  'name' : string,
  'memoryConfig' : string,
  'createdAt' : Timestamp,
  'modeBinding' : EDDIMode,
  'reasoningSeed' : string,
}
export type UserId = Principal;
export interface VaultEntry {
  'subject' : string,
  'contentType' : string,
  'entryId' : string,
  'summary' : string,
  'addedAt' : bigint,
  'gradeLevel' : bigint,
}
export interface VisionDocument {
  'impactCase' : string,
  'liveStats' : VisionStats,
  'platformVision' : string,
  'technicalSovereignty' : string,
  'fundingStrategy' : string,
  'foundingStory' : string,
}
export interface VisionDocumentV2 {
  'impactCase' : string,
  'founderStory' : string,
  'missionStatement' : string,
  'marketGap' : string,
  'generatedBy' : string,
  'version' : string,
  'timestamp' : bigint,
  'fundingSection' : string,
  'diegoProtocol' : string,
  'architectureSection' : string,
}
export interface VisionStats {
  'totalStudentsFlagged' : bigint,
  'achievementsSealed' : bigint,
  'nominationsSent' : bigint,
}
export interface VisionWithFunding {
  'founderStory' : string,
  'totalRecognitions' : bigint,
  'totalStudents' : bigint,
  'activePrograms' : bigint,
  'visionText' : string,
  'fundingTargets' : Array<FundingTarget>,
}
export interface WeekProgress {
  'avgScore' : number,
  'week' : bigint,
  'completedLessons' : bigint,
}
export interface XcrrStats {
  'totalMemberships' : bigint,
  'totalClubs' : bigint,
  'avgMembersPerClub' : bigint,
  'activeClubCount' : bigint,
}
export interface _SERVICE {
  'addAdmissionsEvent' : ActorMethod<[AdmissionsEvent], boolean>,
  'addCalendarEvent' : ActorMethod<[CalendarEvent], undefined>,
  'addCollegeToList' : ActorMethod<[CollegeEntry], boolean>,
  'addCounselorMilestone' : ActorMethod<
    [Principal, CounselorMilestone],
    boolean
  >,
  'addFieldTripAttendee' : ActorMethod<[bigint, Principal], undefined>,
  'addGroupMember' : ActorMethod<[bigint, Principal], boolean>,
  'addScholarshipProgram' : ActorMethod<[ScholarshipProgram], bigint>,
  'addSchoolToDistrict' : ActorMethod<[DistrictId, SchoolId], boolean>,
  'addStaffMember' : ActorMethod<
    [string, string, StaffRole, string, bigint],
    boolean
  >,
  'addSubHandoffNote' : ActorMethod<[bigint, string], undefined>,
  'advanceTrackStep' : ActorMethod<
    [TrackId, [] | [string], bigint],
    { 'ok' : TrackEnrollment } |
      { 'err' : string }
  >,
  'alignContent' : ActorMethod<[StandardAlignment], undefined>,
  'approveClient' : ActorMethod<[string, string], [] | [RegistrationResult]>,
  'archiveTripToPassport' : ActorMethod<[bigint], undefined>,
  'askAgent' : ActorMethod<
    [string, string, string, string, string, bigint],
    string
  >,
  'autoSealFromSession' : ActorMethod<[string, string, string, string], string>,
  'chatWithEddi' : ActorMethod<
    [EDDIMode, string, string],
    {
      'nextModeSuggestion' : [] | [EDDIMode],
      'response' : string,
      'modeUsed' : EDDIMode,
    }
  >,
  'checkGradeAccess' : ActorMethod<[bigint, bigint], GradeGate>,
  'checkOutResource' : ActorMethod<
    [ResourceType, string, string, [] | [bigint]],
    bigint
  >,
  'completeModule' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'completeSelfStudyMilestone' : ActorMethod<[string, bigint], boolean>,
  'completeTestPrepSession' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    boolean
  >,
  'completeTrack' : ActorMethod<
    [TrackId, [] | [string], bigint],
    { 'ok' : TrackEnrollment } |
      { 'err' : string }
  >,
  'completeTutoringSession' : ActorMethod<
    [bigint, bigint, [] | [Uint8Array]],
    boolean
  >,
  'computeCareerRecommendations' : ActorMethod<
    [Array<[bigint, bigint]>],
    Array<CareerCluster>
  >,
  'computeIAS' : ActorMethod<[bigint, bigint], IasResult>,
  'computeImpact' : ActorMethod<[bigint, bigint], ImpactResult>,
  'computeScoreProjection' : ActorMethod<
    [TestPrepMode, bigint],
    ScoreProjection
  >,
  'computeStudentState' : ActorMethod<[bigint], LiveIntelligenceState>,
  'createAgent' : ActorMethod<[string, EDDIMode, string, string], UserAgent>,
  'createAssignment' : ActorMethod<[Assignment], bigint>,
  'createClass' : ActorMethod<
    [string, string, string, bigint, Array<string>],
    boolean
  >,
  'createClub' : ActorMethod<[string, ClubCategory, bigint], bigint>,
  'createCounselorPlan' : ActorMethod<[CounselorPlan], undefined>,
  'createDistrict' : ActorMethod<[string, string, string, bigint], DistrictId>,
  'createFactoryStudent' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createFieldTrip' : ActorMethod<
    [string, bigint, bigint, bigint, string, EnrichmentType],
    bigint
  >,
  'createSelfStudyTrack' : ActorMethod<[string, string, bigint], string>,
  'createSovereignPassport' : ActorMethod<
    [string, string, string],
    SovereignPassport
  >,
  'createStudentProfile' : ActorMethod<[string, string], StudentProfile>,
  'createSubRecord' : ActorMethod<
    [Principal, string, bigint, SubAccessLevel],
    bigint
  >,
  'createTutoringSession' : ActorMethod<[TutoringSession], bigint>,
  'deactivateAccommodations' : ActorMethod<[Principal], boolean>,
  'diagSystem' : ActorMethod<
    [],
    {
      'status' : { 'ok' : null } |
        { 'muta' : null },
      'pilScore' : number,
      'errors' : Array<string>,
      'heartbeatCount' : bigint,
      'avgCoh' : number,
    }
  >,
  'digestCurriculumText' : ActorMethod<
    [string, bigint, string, string, string],
    DigestResult
  >,
  'digestTextbook' : ActorMethod<
    [string, bigint, string, string],
    DigtDigestResult
  >,
  'dissolveClub' : ActorMethod<[bigint], undefined>,
  'dissolveStudyGroup' : ActorMethod<[bigint], boolean>,
  'drainVaultBuffer' : ActorMethod<[], Array<Uint8Array>>,
  'enrollInCourse' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'enrollInCourseWithStart' : ActorMethod<[string], EnrollmentResult>,
  'enrollInTrack' : ActorMethod<
    [TrackId, bigint],
    { 'ok' : TrackEnrollment } |
      { 'err' : string }
  >,
  'enterNexumGate' : ActorMethod<[string, bigint], NexumGateEntry>,
  'executeQuery' : ActorMethod<
    [string, Array<[string, string, string]>, bigint],
    QueryResult
  >,
  'factoryAdminSetup' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'factoryStatus' : ActorMethod<
    [],
    {
      'adminExists' : boolean,
      'factoryLocked' : boolean,
      'studentCount' : bigint,
    }
  >,
  'fireArchCouncil' : ActorMethod<[string, string], MLTVResponse>,
  'flagStudentIep' : ActorMethod<[Principal], boolean>,
  'formStudyGroup' : ActorMethod<
    [bigint, bigint, Array<Principal>, bigint, bigint],
    bigint
  >,
  'generateClassHeatmap' : ActorMethod<[string], [] | [ClassHeatmap]>,
  'generateTeacherRecommendations' : ActorMethod<
    [string],
    Array<TeacherRecommendation>
  >,
  'generateVisionDocument' : ActorMethod<[], VisionDocument>,
  'getAccessibleContent' : ActorMethod<[bigint], Array<GradeVaultEntry>>,
  'getAccommodations' : ActorMethod<[Principal], [] | [IepAccommodation]>,
  'getAchievementGaps' : ActorMethod<[DistrictId], Array<AchievementGapRecord>>,
  'getAchievementTimeline' : ActorMethod<
    [UserId],
    Array<AchievementTimelineEntry>
  >,
  'getAchievements' : ActorMethod<[UserId], Array<AchievementRecord>>,
  'getAdaptiveSuggestion' : ActorMethod<[string], AdaptiveSuggestion>,
  'getAdaptiveWorkflow' : ActorMethod<[string, string], AdaptiveWorkflow>,
  'getAgent' : ActorMethod<[string], [] | [Agent]>,
  'getAgents' : ActorMethod<[], Array<Agent>>,
  'getAgentsByEngine' : ActorMethod<[string], Array<Agent>>,
  'getAgentsByProtocol' : ActorMethod<[string], Array<Agent>>,
  'getAgentsByWorkspace' : ActorMethod<[string], Array<Agent>>,
  'getAlignments' : ActorMethod<[StandardCode], Array<StandardAlignment>>,
  'getAllBuilderStats' : ActorMethod<[], Array<[string, BuilderStats]>>,
  'getAllMoodAggregates' : ActorMethod<[], Array<MoodAggregate>>,
  'getAllRecognitionFlags' : ActorMethod<[], Array<RecognitionFlag>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAllocatorStats' : ActorMethod<[], AllocatorStats>,
  'getAnnouncementsBySchool' : ActorMethod<[bigint], Array<CommMessage>>,
  'getApiCallLogs' : ActorMethod<[bigint], Array<ApiCallLog>>,
  'getApiEndpointById' : ActorMethod<[string], [] | [ApiEndpoint]>,
  'getApiEndpoints' : ActorMethod<[], Array<ApiEndpoint>>,
  'getApiEndpointsByDomain' : ActorMethod<[string], Array<ApiEndpoint>>,
  'getApiStats' : ActorMethod<[], ApiStats>,
  'getApiUsageStats' : ActorMethod<[string], [] | [ApiUsageStats]>,
  'getApiVersions' : ActorMethod<[], Array<ApiVersion>>,
  'getAsgnStats' : ActorMethod<[], AsgnStats>,
  'getAssignment' : ActorMethod<[bigint], [] | [Assignment]>,
  'getAssignmentsByClass' : ActorMethod<[string], Array<Assignment>>,
  'getAttendance' : ActorMethod<[SisStudentId], Array<AttendanceRecord>>,
  'getBuilderStats' : ActorMethod<[string], [] | [BuilderStats]>,
  'getCalendarEvents' : ActorMethod<[bigint], Array<CalendarEvent>>,
  'getCatalog' : ActorMethod<[], Array<CatalogCourse>>,
  'getCheckoutsByStudent' : ActorMethod<[Principal], Array<LibraryRecord>>,
  'getClassAverage' : ActorMethod<[bigint], bigint>,
  'getClassDetail' : ActorMethod<[string], [] | [ClassDetail]>,
  'getClassesByTeacher' : ActorMethod<[string], Array<TeacherClass>>,
  'getClassesByTeacherId' : ActorMethod<[Principal], Array<ClassRecord>>,
  'getClrdStats' : ActorMethod<[], ClrdStats>,
  'getClubEngagementScore' : ActorMethod<[Principal], bigint>,
  'getClubsBySchool' : ActorMethod<[bigint], Array<ClubRecord>>,
  'getCommStats' : ActorMethod<[], CommStats>,
  'getCompetitionTemplates' : ActorMethod<[], Array<CompetitionTemplate>>,
  'getConceptsByGrade' : ActorMethod<[bigint], Array<DigtConcept>>,
  'getCounPlanStats' : ActorMethod<[], CounPlanStats>,
  'getCounselorPlan' : ActorMethod<[Principal], [] | [CounselorPlan]>,
  'getCourseDetail' : ActorMethod<[string], [] | [CatalogCourseDetail]>,
  'getCourses' : ActorMethod<[], Array<CourseSummary>>,
  'getCrossSchoolTrends' : ActorMethod<[DistrictId], Array<CrossSchoolTrend>>,
  'getCrptStats' : ActorMethod<[], CrptStats>,
  'getDemoStudentData' : ActorMethod<
    [],
    {
      'sampleSessions' : Array<QuizResult>,
      'subjects' : Array<Subject>,
      'samplePassport' : SovereignPassport,
    }
  >,
  'getDigestStatus' : ActorMethod<[string], [] | [DigestStatus]>,
  'getDigtStats' : ActorMethod<[], DigtStats>,
  'getDigtStatusForStandard' : ActorMethod<[string], DigtStatus>,
  'getDistrict' : ActorMethod<[DistrictId], [] | [DistrictProfile]>,
  'getDistrictStats' : ActorMethod<[DistrictId], DistrictStats>,
  'getEddi' : ActorMethod<[], EDDI>,
  'getEddiInsight' : ActorMethod<[], string>,
  'getEddiMode' : ActorMethod<[], EDDIMode>,
  'getEngineByCodeName' : ActorMethod<[string], [] | [SovereignEngine]>,
  'getEngineById' : ActorMethod<[bigint], [] | [SovereignEngine]>,
  'getEngines' : ActorMethod<[], Array<SovereignEngine>>,
  'getEnrolledCourses' : ActorMethod<[], Array<EnrolledCourse>>,
  'getEntanglementById' : ActorMethod<[string], [] | [EntanglementRecord]>,
  'getEntanglementStats' : ActorMethod<
    [],
    {
      'totalTransits' : bigint,
      'avgCoherenceDelta' : bigint,
      'lastRefresh' : bigint,
      'activeCount' : bigint,
    }
  >,
  'getEntanglements' : ActorMethod<[], Array<EntanglementRecord>>,
  'getEslProfile' : ActorMethod<[Principal], [] | [EslProfile]>,
  'getEsllStats' : ActorMethod<[], EsllStats>,
  'getFeedbackEvents' : ActorMethod<[], Array<FeedbackEvent>>,
  'getFieldTripsByGrade' : ActorMethod<[bigint], Array<FieldTripRecord>>,
  'getFieldTripsBySchool' : ActorMethod<[bigint], Array<FieldTripRecord>>,
  'getFluxState' : ActorMethod<[string], FluxState>,
  'getFtrpStats' : ActorMethod<[], FtrpStats>,
  'getFullPassportStats' : ActorMethod<[], [] | [PassportStats]>,
  'getFundingTracker' : ActorMethod<[], Array<FundingEntry>>,
  'getGradePerformance' : ActorMethod<[bigint], Array<GradePerformance>>,
  'getGradeVaultContents' : ActorMethod<[bigint], Array<VaultEntry>>,
  'getGradeVaultSummary' : ActorMethod<[bigint], GradeVaultSummary>,
  'getGroupsBySubject' : ActorMethod<[bigint], Array<StudyGroup>>,
  'getGvltStats' : ActorMethod<[], GvltStats>,
  'getHeatmapData' : ActorMethod<[], Array<ClassHeatmapData>>,
  'getIesmStats' : ActorMethod<[], IesmStats>,
  'getKernelSeeds' : ActorMethod<[], Array<KernelSeed>>,
  'getKnowledgeByGrade' : ActorMethod<[KnowledgeQuery], Array<KnowledgeResult>>,
  'getLawById' : ActorMethod<[bigint], [] | [SovereignLaw]>,
  'getLawByLatinName' : ActorMethod<[string], [] | [SovereignLaw]>,
  'getLaws' : ActorMethod<[], Array<SovereignLaw>>,
  'getLbryStats' : ActorMethod<[], LbryStats>,
  'getLessonContent' : ActorMethod<
    [string, string, string],
    {
      'title' : string,
      'practicePrompt' : string,
      'expansionBlock' : string,
      'reviewSummary' : string,
      'introduction' : string,
      'coreConceptBlock' : string,
    }
  >,
  'getLiveIntelligenceState' : ActorMethod<[UserId], LiveIntelligenceState>,
  'getLiveMetrics' : ActorMethod<[], LiveMetrics>,
  'getLiveSessionMetrics' : ActorMethod<[], LiveSessionMetrics>,
  'getMLTVStats' : ActorMethod<[], MLTVStats>,
  'getMembershipsByStudent' : ActorMethod<[Principal], Array<ClubMembership>>,
  'getMessagesForRecipient' : ActorMethod<[RecipientRef], Array<CommMessage>>,
  'getMhckStats' : ActorMethod<
    [],
    { 'schoolsMonitored' : bigint, 'totalCheckIns' : bigint }
  >,
  'getMoodAggregate' : ActorMethod<[bigint], [] | [MoodAggregate]>,
  'getMsryState' : ActorMethod<[string], MsryState>,
  'getMyCareerPathway' : ActorMethod<[], [] | [CareerPathway]>,
  'getMyClubs' : ActorMethod<[], Array<ClubMembership>>,
  'getMyCollegeReadinessRecord' : ActorMethod<
    [],
    [] | [CollegeReadinessRecord]
  >,
  'getMyEnrollments' : ActorMethod<[], Array<TrackEnrollment>>,
  'getMyFeedback' : ActorMethod<[], Array<FeedbackEvent>>,
  'getMyGateEntries' : ActorMethod<[], Array<NexumGateEntry>>,
  'getMyGrades' : ActorMethod<[], Array<GradeRecord>>,
  'getMyLibraryRecords' : ActorMethod<[], Array<LibraryRecord>>,
  'getMyParentRecord' : ActorMethod<[], [] | [ParentRecord]>,
  'getMyPdGrowthScore' : ActorMethod<[], bigint>,
  'getMyPdHours' : ActorMethod<[], bigint>,
  'getMyPdRecords' : ActorMethod<[], Array<PdRecord>>,
  'getMyScholarshipMatches' : ActorMethod<[], Array<ScholarshipMatch>>,
  'getMyStudyGroups' : ActorMethod<[], Array<StudyGroup>>,
  'getMySubRecords' : ActorMethod<[], Array<SubRecord>>,
  'getMySubmissions' : ActorMethod<[], Array<Submission>>,
  'getMyTestPrepSessions' : ActorMethod<[], Array<TestPrepSession>>,
  'getMyTracks' : ActorMethod<[], Array<SelfStudyTrack>>,
  'getMyTutoringSessions' : ActorMethod<[], Array<TutoringSession>>,
  'getNewScholarshipMatches' : ActorMethod<
    [string, bigint],
    Array<ScholarshipMatch>
  >,
  'getNominations' : ActorMethod<[UserId], Array<NominationRecord>>,
  'getNrveState' : ActorMethod<[], NrveState>,
  'getOverdueCheckouts' : ActorMethod<[], Array<LibraryRecord>>,
  'getOwner' : ActorMethod<[], [] | [Principal]>,
  'getParentsByStudent' : ActorMethod<[Principal], Array<ParentRecord>>,
  'getPassportInsight' : ActorMethod<[UserId], PassportInsight>,
  'getPassportSeeds' : ActorMethod<[bigint, bigint], Array<KernelSeed>>,
  'getPassportStats' : ActorMethod<
    [],
    [] | [
      { 'totalSeeds' : bigint, 'totalSessions' : bigint, 'lastActive' : bigint }
    ]
  >,
  'getPdGrowthScore' : ActorMethod<[Principal], bigint>,
  'getPdRecordsByTeacher' : ActorMethod<[Principal], Array<PdRecord>>,
  'getPdTotalHours' : ActorMethod<[Principal], bigint>,
  'getPgrpStats' : ActorMethod<[], PgrpStats>,
  'getPlseState' : ActorMethod<[], PlseState>,
  'getPortalTransitions' : ActorMethod<[bigint], Array<PortalTransition>>,
  'getPrcpNarrative' : ActorMethod<[], Array<PrcpNarrativeEntry>>,
  'getPrincipalGradeDrilldown' : ActorMethod<[bigint], GradeDrilldown>,
  'getPrincipalHeatmapWithNoms' : ActorMethod<[], Array<HeatmapWithNoms>>,
  'getQueryHistory' : ActorMethod<[], Array<QueryResult>>,
  'getQuizSeedsByGrade' : ActorMethod<[bigint], Array<DigtQuizSeed>>,
  'getRcgnAlerts' : ActorMethod<[], Array<RcgnAlert>>,
  'getRecentMLTVResponses' : ActorMethod<[bigint], Array<MLTVResponse>>,
  'getRecognitionFlags' : ActorMethod<[UserId], Array<RecognitionFlag>>,
  'getRecognitionTimeline' : ActorMethod<
    [UserId],
    Array<RecognitionTimelineEntry>
  >,
  'getRegistryQuestion' : ActorMethod<[bigint, string], string>,
  'getRoster' : ActorMethod<[string], [] | [ClassRoster]>,
  'getSchfStats' : ActorMethod<[], SchfStats>,
  'getScholarshipMatches' : ActorMethod<[string], Array<ScholarshipMatch>>,
  'getSdkEntries' : ActorMethod<[], Array<SdkEntry>>,
  'getSdkEntriesByCategory' : ActorMethod<[string], Array<SdkEntry>>,
  'getSdkEntryById' : ActorMethod<[string], [] | [SdkEntry]>,
  'getSelfStudyStats' : ActorMethod<[string], [] | [SelfStudyTrack]>,
  'getSessionCount' : ActorMethod<[], bigint>,
  'getSessionMetrics' : ActorMethod<[], SessionMetrics>,
  'getSessionMode' : ActorMethod<[], SessionMode>,
  'getSessionSchedule' : ActorMethod<[], SessionSchedule>,
  'getSessionsByTutor' : ActorMethod<[string], Array<TutoringSession>>,
  'getSilverBuilderById' : ActorMethod<[string], [] | [SilverBuilder]>,
  'getSilverBuilders' : ActorMethod<[], Array<SilverBuilder>>,
  'getSisAttendance' : ActorMethod<[SisStudentId], Array<AttendanceRecord>>,
  'getSisEnrollments' : ActorMethod<[], Array<SisRecord>>,
  'getSisRecord' : ActorMethod<[SisStudentId], [] | [SisRecord]>,
  'getSisRosters' : ActorMethod<[], Array<ClassRoster>>,
  'getSisStudentData' : ActorMethod<[SisStudentId], [] | [SisRecord]>,
  'getSisSyncStatus' : ActorMethod<
    [],
    {
      'errorMessage' : [] | [string],
      'isHealthy' : boolean,
      'lastSync' : bigint,
      'nextSync' : bigint,
    }
  >,
  'getSkaiDocensInfo' : ActorMethod<[], SkaiDocensInfo>,
  'getSovereignPassport' : ActorMethod<[], [] | [SovereignPassport]>,
  'getStaffActivityLog' : ActorMethod<[string], Array<ActivityEntry>>,
  'getStaffMember' : ActorMethod<[string], [] | [StaffMember]>,
  'getStaffRoster' : ActorMethod<[], Array<StaffMember>>,
  'getStandard' : ActorMethod<[StandardCode], [] | [Standard]>,
  'getStandardsByGrade' : ActorMethod<[bigint], Array<Standard>>,
  'getStandardsBySubject' : ActorMethod<[string], Array<Standard>>,
  'getStandardsWithDigestedContent' : ActorMethod<
    [bigint],
    Array<StandardWithDigestStatus>
  >,
  'getStndStats' : ActorMethod<[], StndStats>,
  'getStudentCountByGrade' : ActorMethod<[], Array<GradeCount>>,
  'getStudentMasteryCard' : ActorMethod<[string], [] | [StudentMasteryCard]>,
  'getStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getStudentQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getStudentRcgnThreshold' : ActorMethod<[UserId], bigint>,
  'getSubRecordsByClass' : ActorMethod<[string], Array<SubRecord>>,
  'getSubRecordsByDate' : ActorMethod<[bigint], Array<SubRecord>>,
  'getSubjectTemplates' : ActorMethod<[GradeLevel], Array<SubjectTemplate>>,
  'getSubjectsByGrade' : ActorMethod<[string], Array<Subject>>,
  'getSubmissionsByAssignment' : ActorMethod<[bigint], Array<Submission>>,
  'getSubsStats' : ActorMethod<[], SubsStats>,
  'getSystemMetricsSummary' : ActorMethod<[], SystemMetrics>,
  'getTchrStats' : ActorMethod<[], TchrStats>,
  'getTeacherClassMetrics' : ActorMethod<[string], Array<TeacherClassMetrics>>,
  'getTopicsBySubject' : ActorMethod<[string], Array<Topic>>,
  'getTpdfStats' : ActorMethod<[], TpdfStats>,
  'getTprpStats' : ActorMethod<[], TprpStats>,
  'getTrackById' : ActorMethod<[TrackId], [] | [Track]>,
  'getTracks' : ActorMethod<[], Array<Track>>,
  'getTutoringStats' : ActorMethod<[], { 'total' : bigint, 'sealed' : bigint }>,
  'getUnreadCount' : ActorMethod<[RecipientRef], bigint>,
  'getUserAgents' : ActorMethod<[], Array<UserAgent>>,
  'getVaultCanisterId' : ActorMethod<[], [] | [Principal]>,
  'getVaultStats' : ActorMethod<
    [],
    {
      'totalBytesBuffered' : bigint,
      'lastDrainAt' : bigint,
      'totalPayloads' : bigint,
    }
  >,
  'getVisionDocumentV2' : ActorMethod<[], VisionDocumentV2>,
  'getVisionStats' : ActorMethod<[], VisionStats>,
  'getVisionWithFundingTracker' : ActorMethod<[], VisionWithFunding>,
  'getWorkspaces' : ActorMethod<[], Array<string>>,
  'getXcrrStats' : ActorMethod<[], XcrrStats>,
  'gradeSubmission' : ActorMethod<[GradeRecord], bigint>,
  'hasAccommodation' : ActorMethod<[Principal, AccommodationType], boolean>,
  'inferEddiMode' : ActorMethod<[string], EDDIMode>,
  'initFactory' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'isFactoryInitialized' : ActorMethod<[], boolean>,
  'joinClub' : ActorMethod<[bigint, ClubRole], undefined>,
  'linkClubAchievement' : ActorMethod<[bigint, Principal, bigint], undefined>,
  'linkFieldTripPreAssessment' : ActorMethod<[bigint, bigint], undefined>,
  'linkStudentToParent' : ActorMethod<[Principal], boolean>,
  'linkToSubject' : ActorMethod<[bigint, bigint], undefined>,
  'listDigestJobs' : ActorMethod<[], Array<DigestJob>>,
  'listPendingRegistrations' : ActorMethod<[], Array<RegistrationRequest>>,
  'listStaff' : ActorMethod<[], Array<StaffMember>>,
  'logApiCall' : ActorMethod<[string, string, bigint, boolean], undefined>,
  'logClubHours' : ActorMethod<[bigint, Principal, bigint], undefined>,
  'logPdRecord' : ActorMethod<
    [string, PdType, bigint, string, [] | [string], [] | [GrowthMilestone]],
    bigint
  >,
  'logPortalTransition' : ActorMethod<[string, string, string], undefined>,
  'logSubIncident' : ActorMethod<[bigint, string, IncidentSeverity], undefined>,
  'markMessageRead' : ActorMethod<[bigint], undefined>,
  'matchStudentToScholarships' : ActorMethod<
    [Array<string>, bigint],
    Array<ScholarshipMatch>
  >,
  'queryEngine' : ActorMethod<[string, string, string], string>,
  'queryEngineWithPassport' : ActorMethod<
    [string, string, string],
    { 'seedGenerated' : KernelSeed, 'response' : string }
  >,
  'recognizeStudent' : ActorMethod<
    [UserId, string, bigint],
    { 'flagCreated' : boolean, 'isGold' : boolean, 'rcgnT' : bigint }
  >,
  'recordAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'recordCareerExploration' : ActorMethod<[CareerExplorationEntry], boolean>,
  'recordEchoEvent' : ActorMethod<[string, string, bigint, bigint], EchoResult>,
  'recordEntanglementTransit' : ActorMethod<[string, bigint], undefined>,
  'recordFundingEntry' : ActorMethod<[FundingEntryInput], FundingEntryResult>,
  'recordMissedSession' : ActorMethod<[], undefined>,
  'recordStudyGroupSession' : ActorMethod<[GroupSession], bigint>,
  'registerApiCaller' : ActorMethod<
    [string, string, string, Array<string>],
    boolean
  >,
  'registerExternalClient' : ActorMethod<
    [string, string, string, Array<string>],
    RegistrationRequest
  >,
  'registerParent' : ActorMethod<[string, ContactPreferences], undefined>,
  'registerStandard' : ActorMethod<[Standard], undefined>,
  'registerVaultContent' : ActorMethod<
    [string, string, bigint, string, bigint],
    boolean
  >,
  'removeFieldTripAttendee' : ActorMethod<[bigint, Principal], undefined>,
  'removeGroupMember' : ActorMethod<[bigint, Principal], boolean>,
  'resolveFeedback' : ActorMethod<[string], boolean>,
  'returnResource' : ActorMethod<[bigint], undefined>,
  'runHeartbeat' : ActorMethod<[], Array<Uint8Array>>,
  'runRCGNScan' : ActorMethod<[], Array<RecognitionFlag>>,
  'saveQuizResult' : ActorMethod<[QuizResult], undefined>,
  'saveSessionMode' : ActorMethod<[SessionMode], undefined>,
  'sealKernelSeed' : ActorMethod<[KernelSeed], boolean>,
  'seedCurriculumIfEmpty' : ActorMethod<[], string>,
  'sendAnnouncement' : ActorMethod<[bigint, string, string], bigint>,
  'sendCommMessage' : ActorMethod<
    [Array<RecipientRef>, string, string, MessageType, boolean, [] | [bigint]],
    bigint
  >,
  'setAccommodations' : ActorMethod<[IepAccommodation], undefined>,
  'setEddiMode' : ActorMethod<[EDDIMode], undefined>,
  'setEslScaffolding' : ActorMethod<[Principal, boolean], boolean>,
  'setVaultCanisterId' : ActorMethod<[Principal], undefined>,
  'skaiRoute' : ActorMethod<[string, string, string], string>,
  'skaiTeach' : ActorMethod<[string], SkaiTeachResponse>,
  'sonrCheck' : ActorMethod<[], SonrStatus>,
  'startTestPrepSession' : ActorMethod<[TestPrepMode, bigint, bigint], bigint>,
  'submitAssignment' : ActorMethod<[Submission], bigint>,
  'submitFeedback' : ActorMethod<[string, string], string>,
  'submitMoodCheckIn' : ActorMethod<[MentalHealthCheckIn], undefined>,
  'submitNomination' : ActorMethod<[UserId, string, string], NominationRecord>,
  'tickEntanglementCycle' : ActorMethod<[], undefined>,
  'updateCounselorPlan' : ActorMethod<[Principal, CounselorPlan], boolean>,
  'updateMemberRole' : ActorMethod<[bigint, Principal, ClubRole], undefined>,
  'updateParentPermission' : ActorMethod<[PermissionLevel], boolean>,
  'updateReadingProgress' : ActorMethod<[bigint, bigint], undefined>,
  'updateScholarshipStatus' : ActorMethod<[bigint, ApplicationStatus], boolean>,
  'updateSessionMode' : ActorMethod<[SessionMode], undefined>,
  'updateStaffRole' : ActorMethod<[string, StaffRole], boolean>,
  'updateStudentGrade' : ActorMethod<[string], StudentProfile>,
  'updateStudentMasteryScore' : ActorMethod<
    [string, string, bigint],
    undefined
  >,
  'upsertCareerPathway' : ActorMethod<[CareerPathway], bigint>,
  'upsertCollegeReadinessRecord' : ActorMethod<
    [CollegeReadinessRecord],
    undefined
  >,
  'upsertEslProfile' : ActorMethod<[EslProfile], undefined>,
  'upsertRoster' : ActorMethod<[ClassRoster], undefined>,
  'upsertSisRecord' : ActorMethod<[SisRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];